// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: activity.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace Msg
{

    [global::ProtoBuf.ProtoContract()]
    public partial class GetActivityInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ActivityInfoRes : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public uint FirstRechargeStatus { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public SevenDayGifData sevenDayGifInfo { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public DaySignData daySignInfo { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public TruntableInfo tableInfo { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SevenDayGifData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public ulong BuyTime { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public ulong GetTime { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public uint GetCounts { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetSevenDayGiftReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetSevenDayGiftRes : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"result")]
        public GetSevenDayGifResult Result { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public ulong GetTime { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public enum GetSevenDayGifResult
        {
            [global::ProtoBuf.ProtoEnum(Name = @"GSDGR_Success")]
            GSDGRSuccess = 0,
            [global::ProtoBuf.ProtoEnum(Name = @"GSDGR_AlreadyGet")]
            GSDGRAlreadyGet = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"GSDGR_Lock")]
            GSDGRLock = 2,
            [global::ProtoBuf.ProtoEnum(Name = @"GSDGR_OtherError")]
            GSDGROtherError = 3,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class DaySignData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public ulong FirstSignTime { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public ulong LastSignTime { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public uint SignCounts { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public uint SingRewardIndex { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public uint VipReward { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetDaySignRewardReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public GetDaySignRewardType daySignType { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public uint RewardIndex { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public enum GetDaySignRewardType
        {
            [global::ProtoBuf.ProtoEnum(Name = @"GDSRT_Normal")]
            GDSRTNormal = 0,
            [global::ProtoBuf.ProtoEnum(Name = @"GDSRT_Vip")]
            GDSRTVip = 1,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetDaySignRewardRes : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"result")]
        public GetDaySignRewardResult Result { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public ulong GetTime { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public enum GetDaySignRewardResult
        {
            [global::ProtoBuf.ProtoEnum(Name = @"GDSRR_Success")]
            GDSRRSuccess = 0,
            [global::ProtoBuf.ProtoEnum(Name = @"GDSRR_AlreadyGet")]
            GDSRRAlreadyGet = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"GDSRR_Lock")]
            GDSRRLock = 2,
            [global::ProtoBuf.ProtoEnum(Name = @"GDSRR_OtherError")]
            GDSRROtherError = 3,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetFirstRewardHero : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public uint HeroID { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetFirstRewardHeroRes : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"result")]
        public GetFirstHeroResult Result { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public uint HeroID { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public enum GetFirstHeroResult
        {
            [global::ProtoBuf.ProtoEnum(Name = @"GFHR_Success")]
            GFHRSuccess = 0,
            [global::ProtoBuf.ProtoEnum(Name = @"GFHR_Fail")]
            GFHRFail = 1,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class TruntableInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public uint TruntableCounts { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public ulong TruntableTime { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class TurnTheTurntable : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class TruntableResult : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"result")]
        public TurnTheTurntableResult Result { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public uint TurnGetId { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public enum TurnTheTurntableResult
        {
            [global::ProtoBuf.ProtoEnum(Name = @"TTTR_Success")]
            TTTRSuccess = 0,
            [global::ProtoBuf.ProtoEnum(Name = @"TTTR_NoCounts")]
            TTTRNoCounts = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"TTTR_RewardCfgError")]
            TTTRRewardCfgError = 2,
            [global::ProtoBuf.ProtoEnum(Name = @"TTTR_OtherError")]
            TTTROtherError = 3,
        }

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
