// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: game.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace Msg
{

    [global::ProtoBuf.ProtoContract()]
    public partial class EnterGameReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public PlayGameType enterType { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public uint ChapterLevel { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GameSceneData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class EnterGameRes : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public EnterGameRulsut enterCode { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public ulong SparSchedule { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public enum EnterGameRulsut
        {
            [global::ProtoBuf.ProtoEnum(Name = @"EGR_Success")]
            EGRSuccess = 0,
            [global::ProtoBuf.ProtoEnum(Name = @"EGR_LockChapter")]
            EGRLockChapter = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"EGR_OtherErro")]
            EGROtherErro = 2,
            [global::ProtoBuf.ProtoEnum(Name = @"EGR_SparNotEnough")]
            EGRSparNotEnough = 3,
            [global::ProtoBuf.ProtoEnum(Name = @"EGR_UnkownType")]
            EGRUnkownType = 4,
            [global::ProtoBuf.ProtoEnum(Name = @"EGR_LimitEnter")]
            EGRLimitEnter = 5,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AttackMonsterReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"MonsterIDList", IsPacked = true)]
        public long[] MonsterIDLists { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public ulong Bullet { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"MonsterCfgList", IsPacked = true)]
        public int[] MonsterCfgLists { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public uint RageType { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public int ReqId { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AttackMonsterRes : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public long MonsterID { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"code")]
        public AttackCode Code { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public ulong Consume { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public ulong Remaining { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public ulong Get { get; set; }

        [global::ProtoBuf.ProtoMember(6)]
        public long AttackTime { get; set; }

        [global::ProtoBuf.ProtoMember(7)]
        public ulong SparSchedule { get; set; }

        [global::ProtoBuf.ProtoMember(8)]
        public int BossSchedule { get; set; }

        [global::ProtoBuf.ProtoMember(9)]
        public int GetModaoshi { get; set; }

        [global::ProtoBuf.ProtoMember(10)]
        public long TotalUseSpar { get; set; }

        [global::ProtoBuf.ProtoMember(11)]
        public int ReqId { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public enum AttackCode
        {
            [global::ProtoBuf.ProtoEnum(Name = @"ACTC_Success")]
            ACTCSuccess = 0,
            [global::ProtoBuf.ProtoEnum(Name = @"ACTC_Fail")]
            ACTCFail = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"ACTC_NoAmmo")]
            ACTCNoAmmo = 2,
            [global::ProtoBuf.ProtoEnum(Name = @"ACTC_IllegalAttack")]
            ACTCIllegalAttack = 3,
            [global::ProtoBuf.ProtoEnum(Name = @"ACTC_IllegalMonster")]
            ACTCIllegalMonster = 4,
            [global::ProtoBuf.ProtoEnum(Name = @"ACTC_IllegalBullet")]
            ACTCIllegalBullet = 5,
            [global::ProtoBuf.ProtoEnum(Name = @"ACTC_IllegalGameStatus")]
            ACTCIllegalGameStatus = 6,
            [global::ProtoBuf.ProtoEnum(Name = @"ACTC_OtherErr")]
            ACTCOtherErr = 7,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ExitGame : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GameEnd : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public PlayGameType gameType { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public GamePassType passType { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public enum GamePassType
        {
            [global::ProtoBuf.ProtoEnum(Name = @"GPT_BoosDie")]
            GPTBoosDie = 0,
            [global::ProtoBuf.ProtoEnum(Name = @"GPT_PlayerDie")]
            GPTPlayerDie = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"GPT_PlayerOut")]
            GPTPlayerOut = 2,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GameEndRes : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public PlayGameType gameType { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public ulong GetGold { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public ulong Modaoshi { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public uint PlayerChapter { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class EndelessBoosRefresh : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class EndelessBoosDie : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class EndelessBoosReward : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public ulong GetModaoshi { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public uint DropGear { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public KillBossResultCode KillCode { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public enum KillBossResultCode
        {
            [global::ProtoBuf.ProtoEnum(Name = @"KBRC_Normal")]
            KBRCNormal = 0,
            [global::ProtoBuf.ProtoEnum(Name = @"KBRC_SceneError")]
            KBRCSceneError = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"KBRC_Unsatisfactory")]
            KBRCUnsatisfactory = 2,
            [global::ProtoBuf.ProtoEnum(Name = @"KBRC_OtherErro")]
            KBRCOtherErro = 3,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class BulletExpChange : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public long BulletExp { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class BulletLevelUpReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class BulletLevelUpRes : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public BulletLevelUpResult Result { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public enum BulletLevelUpResult
        {
            [global::ProtoBuf.ProtoEnum(Name = @"BLUR_Success")]
            BLURSuccess = 0,
            [global::ProtoBuf.ProtoEnum(Name = @"BLUR_NoExp")]
            BLURNoExp = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"BLUR_Erro")]
            BLURErro = 2,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetModaoshiPoolPlayerInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int PlayerId { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public long Modaoshi { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public int PlayerVip { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public long DropTime { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public int MonsterID { get; set; }

        [global::ProtoBuf.ProtoMember(6)]
        [global::System.ComponentModel.DefaultValue("")]
        public string Nickname { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ModaoshiPoolNotice : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public ulong ModaoshiPool { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"CarveUpInfo")]
        public global::System.Collections.Generic.List<GetModaoshiPoolPlayerInfo> CarveUpInfoes { get; } = new global::System.Collections.Generic.List<GetModaoshiPoolPlayerInfo>();

    }

    [global::ProtoBuf.ProtoContract()]
    public enum PlayGameType
    {
        [global::ProtoBuf.ProtoEnum(Name = @"PGT_Levels")]
        PGTLevels = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"PGT_Endless")]
        PGTEndless = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"PGT_Endless_Beginner")]
        PGTEndlessBeginner = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"PGT_Endless_Intermediate")]
        PGTEndlessIntermediate = 3,
        [global::ProtoBuf.ProtoEnum(Name = @"PGT_Endless_Bonus")]
        PGTEndlessBonus = 4,
    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
