// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: hall.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace Msg
{

    [global::ProtoBuf.ProtoContract()]
    public partial class FullServiceBroadcast : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        [global::System.ComponentModel.DefaultValue("")]
        public string BroadcastMsg { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SysMsg : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public SysMsgType MsgType { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue("")]
        public string MsgText { get; set; } = "";

        [global::ProtoBuf.ProtoContract()]
        public enum SysMsgType
        {
            [global::ProtoBuf.ProtoEnum(Name = @"SYSMT_Normal")]
            SYSMTNormal = 0,
            [global::ProtoBuf.ProtoEnum(Name = @"SYSMT_Close")]
            SYSMTClose = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"SYSMT_BackLogin")]
            SYSMTBackLogin = 2,
            [global::ProtoBuf.ProtoEnum(Name = @"SYSMT_BackHall")]
            SYSMTBackHall = 3,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetSupplyReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"gtype")]
        public SupplyType Gtype { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetSupplyRes : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public GetSupplyResult gCode { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"stype")]
        public SupplyType Stype { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public uint SupplyGet { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public long Time { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public enum GetSupplyResult
        {
            [global::ProtoBuf.ProtoEnum(Name = @"GSR_OK")]
            GsrOk = 0,
            [global::ProtoBuf.ProtoEnum(Name = @"GSR_TimeOut")]
            GSRTimeOut = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"GSR_TypeErro")]
            GSRTypeErro = 2,
            [global::ProtoBuf.ProtoEnum(Name = @"GSR_OterErro")]
            GSROterErro = 3,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class UpgradeEquipReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public uint UpgradePos { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class UpgradeEquipRes : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public uint UpgradePos { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public UpgradeResult upCode { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public uint UpLevel { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public enum UpgradeResult
        {
            [global::ProtoBuf.ProtoEnum(Name = @"UPE_Success")]
            UPESuccess = 0,
            [global::ProtoBuf.ProtoEnum(Name = @"UPE_NoGold")]
            UPENoGold = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"UPE_AlreadyMax")]
            UPEAlreadyMax = 2,
            [global::ProtoBuf.ProtoEnum(Name = @"UPE_NoStone")]
            UPENoStone = 3,
            [global::ProtoBuf.ProtoEnum(Name = @"UPE_Fail")]
            UPEFail = 4,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AddTalentReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public AddTalentType atType { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public uint TalentLv { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AddTalentRes : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public AddTalentType atType { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public AddTalentResult atrCode { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public uint AddTalentLevel { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public enum AddTalentResult
        {
            [global::ProtoBuf.ProtoEnum(Name = @"ATTR_Success")]
            ATTRSuccess = 0,
            [global::ProtoBuf.ProtoEnum(Name = @"ATTR_NoGold")]
            ATTRNoGold = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"ATTR_AlreadyMax")]
            ATTRAlreadyMax = 2,
            [global::ProtoBuf.ProtoEnum(Name = @"ATTR_TypeErro")]
            ATTRTypeErro = 3,
            [global::ProtoBuf.ProtoEnum(Name = @"ATTR_LvErro")]
            ATTRLvErro = 4,
            [global::ProtoBuf.ProtoEnum(Name = @"ATTR_Fail")]
            ATTRFail = 5,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ChangeGuide : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public uint changeVulue { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ChangeGuideRes : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public uint GuidIndex { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class NewServerDay : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public long ServerTime { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ThirdUseModaoshi : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public ulong RestModaoshi { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public ulong UseModaoshi { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetPassGift : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int RewardPos { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetPassGiftRes : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"result")]
        public GetPassGitResult Result { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public enum GetPassGitResult
        {
            [global::ProtoBuf.ProtoEnum(Name = @"GPGR_Success")]
            GPGRSuccess = 0,
            [global::ProtoBuf.ProtoEnum(Name = @"GPGR_PassLvErro")]
            GPGRPassLvErro = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"GPGR_AlreadyGet")]
            GPGRAlreadyGet = 2,
            [global::ProtoBuf.ProtoEnum(Name = @"GPGR_Erro")]
            GPGRErro = 3,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class DeleteAccountReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class DeleteAccountRes : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public DeleteAccountResult Result { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public enum DeleteAccountResult
        {
            [global::ProtoBuf.ProtoEnum(Name = @"DAR_Success")]
            DARSuccess = 0,
            [global::ProtoBuf.ProtoEnum(Name = @"DAR_Fail")]
            DARFail = 1,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetMoneyToAliEnd : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        [global::System.ComponentModel.DefaultValue("")]
        public string AliAccount { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetMoneyToAliEndRes : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"result")]
        public GetMoneyToAliResult Result { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public ulong Modaoshi { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public enum GetMoneyToAliResult
        {
            [global::ProtoBuf.ProtoEnum(Name = @"GMTALR_Success")]
            GMTALRSuccess = 0,
            [global::ProtoBuf.ProtoEnum(Name = @"GMTALR_AlreadyGet")]
            GMTALRAlreadyGet = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"GMTALR_NoName")]
            GMTALRNoName = 2,
            [global::ProtoBuf.ProtoEnum(Name = @"GMTALR_NoModaoshi")]
            GMTALRNoModaoshi = 3,
            [global::ProtoBuf.ProtoEnum(Name = @"GMTALR_NoToken")]
            GMTALRNoToken = 4,
            [global::ProtoBuf.ProtoEnum(Name = @"GMTALR_Fail")]
            GMTALRFail = 5,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ChangePlayerInfoReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public ChangePlayerInfoType ChangeType { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue("")]
        public string Name
        {
            get => __pbn__ChangeData.Is(2) ? ((string)__pbn__ChangeData.Object) : "";
            set => __pbn__ChangeData = new global::ProtoBuf.DiscriminatedUnion32Object(2, value);
        }
        public bool ShouldSerializeName() => __pbn__ChangeData.Is(2);
        public void ResetName() => global::ProtoBuf.DiscriminatedUnion32Object.Reset(ref __pbn__ChangeData, 2);

        private global::ProtoBuf.DiscriminatedUnion32Object __pbn__ChangeData;

        [global::ProtoBuf.ProtoMember(3)]
        public int Head
        {
            get => __pbn__ChangeData.Is(3) ? __pbn__ChangeData.Int32 : default;
            set => __pbn__ChangeData = new global::ProtoBuf.DiscriminatedUnion32Object(3, value);
        }
        public bool ShouldSerializeHead() => __pbn__ChangeData.Is(3);
        public void ResetHead() => global::ProtoBuf.DiscriminatedUnion32Object.Reset(ref __pbn__ChangeData, 3);

        [global::ProtoBuf.ProtoContract()]
        public enum ChangePlayerInfoType
        {
            [global::ProtoBuf.ProtoEnum(Name = @"CPIT_Head")]
            CPITHead = 0,
            [global::ProtoBuf.ProtoEnum(Name = @"CPIT_Name")]
            CPITName = 1,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ChangePlayerInfoRes : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public ChangePlayerInfoResult Result { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue("")]
        public string NewName
        {
            get => __pbn__NewData.Is(2) ? ((string)__pbn__NewData.Object) : "";
            set => __pbn__NewData = new global::ProtoBuf.DiscriminatedUnion32Object(2, value);
        }
        public bool ShouldSerializeNewName() => __pbn__NewData.Is(2);
        public void ResetNewName() => global::ProtoBuf.DiscriminatedUnion32Object.Reset(ref __pbn__NewData, 2);

        private global::ProtoBuf.DiscriminatedUnion32Object __pbn__NewData;

        [global::ProtoBuf.ProtoMember(3)]
        public int NewHead
        {
            get => __pbn__NewData.Is(3) ? __pbn__NewData.Int32 : default;
            set => __pbn__NewData = new global::ProtoBuf.DiscriminatedUnion32Object(3, value);
        }
        public bool ShouldSerializeNewHead() => __pbn__NewData.Is(3);
        public void ResetNewHead() => global::ProtoBuf.DiscriminatedUnion32Object.Reset(ref __pbn__NewData, 3);

        [global::ProtoBuf.ProtoContract()]
        public enum ChangePlayerInfoResult
        {
            [global::ProtoBuf.ProtoEnum(Name = @"CPIR_Success")]
            CPIRSuccess = 0,
            [global::ProtoBuf.ProtoEnum(Name = @"CPIR_NameRepeat")]
            CPIRNameRepeat = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"CPIR_HeadIndexErr")]
            CPIRHeadIndexErr = 2,
            [global::ProtoBuf.ProtoEnum(Name = @"CPIR_IsHeading")]
            CPIRIsHeading = 3,
            [global::ProtoBuf.ProtoEnum(Name = @"CPIR_Fail")]
            CPIRFail = 4,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class TriggerPlayerInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public long PlayerID { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue("")]
        public string PlayerName { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3)]
        public int PlayerVip { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public int AtScene { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ShowPaomadengMsg : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public TriggerPlayerInfo TriggerPlayer { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public TriggerTargetType TargetType { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public int TargetID { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public int Number { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public enum TriggerTargetType
        {
            [global::ProtoBuf.ProtoEnum(Name = @"TTT_ActMonsterDropSpar")]
            TTTActMonsterDropSpar = 0,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RankInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int PlayerID { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public int PlayerHead { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        [global::System.ComponentModel.DefaultValue("")]
        public string PlayerName { get; set; } = "";

        [global::ProtoBuf.ProtoMember(4)]
        public long RankNumber { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public int RankType { get; set; }

        [global::ProtoBuf.ProtoMember(6)]
        public int Rank { get; set; }

        [global::ProtoBuf.ProtoMember(7)]
        public int PlayerVip { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class OwnRankInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public long RankSpar { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public long RankModaohi { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public int PassChapterLv { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GameRankDatas : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"SparRank")]
        public global::System.Collections.Generic.List<RankInfo> SparRanks { get; } = new global::System.Collections.Generic.List<RankInfo>();

        [global::ProtoBuf.ProtoMember(2, Name = @"ModaoshiRank")]
        public global::System.Collections.Generic.List<RankInfo> ModaoshiRanks { get; } = new global::System.Collections.Generic.List<RankInfo>();

        [global::ProtoBuf.ProtoMember(3, Name = @"PassLvRank")]
        public global::System.Collections.Generic.List<RankInfo> PassLvRanks { get; } = new global::System.Collections.Generic.List<RankInfo>();

        [global::ProtoBuf.ProtoMember(4)]
        public OwnRankInfo OwnRank { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public enum SupplyType
    {
        [global::ProtoBuf.ProtoEnum(Name = @"ST_Diamond")]
        STDiamond = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"ST_Gold")]
        STGold = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"ST_Spar")]
        STSpar = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"ST_VipBox")]
        STVipBox = 3,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum AddTalentType
    {
        [global::ProtoBuf.ProtoEnum(Name = @"ATT_Damage")]
        ATTDamage = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"ATT_HP")]
        AttHp = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"ATT_CriticalHit")]
        ATTCriticalHit = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"ATT_SpecialSkill")]
        ATTSpecialSkill = 3,
    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
