// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: login.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace Msg
{

    [global::ProtoBuf.ProtoContract()]
    public partial class SignUpResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int errorCode { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"version")]
        public float Version { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class VerificationCodeLogin : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        [global::System.ComponentModel.DefaultValue("")]
        public string phoneNumber { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"code")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Code { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"channel")]
        public int Channel { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public int packVersion { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PhoneNumberLogin : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"account")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Account { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"channel")]
        public int Channel { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public int packVersion { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Login : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"account")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Account { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"passward")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Passward { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"channel")]
        public int Channel { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public int packVersion { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PlayerBaseInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public uint PlayerID { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue("")]
        public string Name { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3)]
        public ulong Spar { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public ulong Modaoshi { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public uint Diamond { get; set; }

        [global::ProtoBuf.ProtoMember(6)]
        public uint GuideIndex { get; set; }

        [global::ProtoBuf.ProtoMember(7)]
        public uint VipLevel { get; set; }

        [global::ProtoBuf.ProtoMember(8)]
        public uint VipExp { get; set; }

        [global::ProtoBuf.ProtoMember(9)]
        public int CertificationIndex { get; set; }

        [global::ProtoBuf.ProtoMember(10)]
        public int ChallengeTickets { get; set; }

        [global::ProtoBuf.ProtoMember(11)]
        public long ServerTime { get; set; }

        [global::ProtoBuf.ProtoMember(12)]
        public ulong Gold { get; set; }

        [global::ProtoBuf.ProtoMember(13)]
        public uint Chapter { get; set; }

        [global::ProtoBuf.ProtoMember(14)]
        public int PassLevelGift { get; set; }

        [global::ProtoBuf.ProtoMember(15)]
        public int MaxBullet { get; set; }

        [global::ProtoBuf.ProtoMember(16)]
        public int BulletExp { get; set; }

        [global::ProtoBuf.ProtoMember(17)]
        [global::System.ComponentModel.DefaultValue("")]
        public string Realname { get; set; } = "";

        [global::ProtoBuf.ProtoMember(18)]
        public long TotalUseSpar { get; set; }

        [global::ProtoBuf.ProtoMember(19)]
        public int DayRecharge { get; set; }

        [global::ProtoBuf.ProtoMember(20)]
        public bool IsNew { get; set; }

        [global::ProtoBuf.ProtoMember(21)]
        public int HeadIndex { get; set; }

        [global::ProtoBuf.ProtoMember(22)]
        public int IsDevice { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PlayerSupplyInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public long DiamondSupplyTime { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public long GoldSupplyTime { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public long SparTime { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public long VipboxTime { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class EquipInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public uint EquipPos { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public uint EquipLevel { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PlayerEquipInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"einfo")]
        public global::System.Collections.Generic.List<EquipInfo> Einfoes { get; } = new global::System.Collections.Generic.List<EquipInfo>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class HeroCard : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int HeroCardID { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public int CardStatus { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PlayerHeroCard : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"cardinfo")]
        public global::System.Collections.Generic.List<HeroCard> Cardinfoes { get; } = new global::System.Collections.Generic.List<HeroCard>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class TalentInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int HpLevel { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public int DamageLevel { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public int CriticalhitLevel { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public int SpecialLevel { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class BagItem : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public uint ItemID { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public uint ItemCount { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class BagInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"bagList")]
        public global::System.Collections.Generic.List<BagItem> bagLists { get; } = new global::System.Collections.Generic.List<BagItem>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RMBGoodsBuyInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public uint GoodsId { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public ulong BuyTime { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public uint BuyCounts { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ThirdShopInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int IsShow { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue("")]
        public string Shoptoken { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3)]
        [global::System.ComponentModel.DefaultValue("")]
        public string AppId { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class LoginSuccessfull : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public PlayerBaseInfo playerBaseInfo { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public PlayerEquipInfo equipInfo { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public PlayerHeroCard heroCardList { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public BagInfo bagList { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public PlayerSupplyInfo supplyInfo { get; set; }

        [global::ProtoBuf.ProtoMember(6)]
        public ActivityInfoRes activtyInfo { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"modaoshiGoodsInfo")]
        public global::System.Collections.Generic.List<ModaoshiGoodsInfo> modaoshiGoodsInfoes { get; } = new global::System.Collections.Generic.List<ModaoshiGoodsInfo>();

        [global::ProtoBuf.ProtoMember(8, Name = @"RMBGoodsList")]
        public global::System.Collections.Generic.List<RMBGoodsBuyInfo> RMBGoodsLists { get; } = new global::System.Collections.Generic.List<RMBGoodsBuyInfo>();

        [global::ProtoBuf.ProtoMember(9, Name = @"mailData")]
        public global::System.Collections.Generic.List<MailData> mailDatas { get; } = new global::System.Collections.Generic.List<MailData>();

        [global::ProtoBuf.ProtoMember(10)]
        public RechargeCardInfo rechargeCardInfo { get; set; }

        [global::ProtoBuf.ProtoMember(11)]
        public DayChallengeInfo chanllengeInfo { get; set; }

        [global::ProtoBuf.ProtoMember(12)]
        public ThirdShopInfo ThirdShop { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class LoginFaild : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"code")]
        public ErrorCode Code { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public enum ErrorCode
        {
            AccountOrPasswardNotMatch = 0,
            AccountInvalid = 1,
            LoginRepeat = 2,
            InnerError = 3,
            VerificationCodeErro = 4,
            ErrorChannel = 5,
            AccountLock = 6,
            BlackListUser = 7,
            DeleteAccount = 8,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AuthenticationInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        [global::System.ComponentModel.DefaultValue("")]
        public string RealName { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue("")]
        public string CardId { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AuthenticationInfoRes : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public uint certificationIndex { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class HeartBeat : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class UpdatePlayerDeviceInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int DeviceType { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue("")]
        public string Idfa { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3)]
        [global::System.ComponentModel.DefaultValue("")]
        public string Imei { get; set; } = "";

        [global::ProtoBuf.ProtoMember(4)]
        [global::System.ComponentModel.DefaultValue("")]
        public string Imei2 { get; set; } = "";

        [global::ProtoBuf.ProtoMember(5)]
        [global::System.ComponentModel.DefaultValue("")]
        public string Meid { get; set; } = "";

        [global::ProtoBuf.ProtoMember(6)]
        [global::System.ComponentModel.DefaultValue("")]
        public string Oaid { get; set; } = "";

        [global::ProtoBuf.ProtoMember(7)]
        [global::System.ComponentModel.DefaultValue("")]
        public string Oaid2 { get; set; } = "";

        [global::ProtoBuf.ProtoMember(8)]
        [global::System.ComponentModel.DefaultValue("")]
        public string Channel { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class UpdatePlayerDeviceInfoRes : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int Result { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public int BindChannel { get; set; }

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
