// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: mail.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace Msg
{

    [global::ProtoBuf.ProtoContract()]
    public partial class MailData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public ulong MailID { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue("")]
        public string MailTitle { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3)]
        [global::System.ComponentModel.DefaultValue("")]
        public string MailText { get; set; } = "";

        [global::ProtoBuf.ProtoMember(4)]
        public uint MailStatus { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public long MailSendTime { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"items")]
        public global::System.Collections.Generic.List<MailItem> Items { get; } = new global::System.Collections.Generic.List<MailItem>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MailItem : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public MailItemType itemType { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public ulong ItemCounts { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public uint ItemID { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public uint VipExp { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public enum MailItemType
        {
            [global::ProtoBuf.ProtoEnum(Name = @"MIT_Spar")]
            MITSpar = 0,
            [global::ProtoBuf.ProtoEnum(Name = @"MIT_Diamond")]
            MITDiamond = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"MIT_Modaoshi")]
            MITModaoshi = 2,
            [global::ProtoBuf.ProtoEnum(Name = @"MIT_Item")]
            MITItem = 3,
            [global::ProtoBuf.ProtoEnum(Name = @"MIT_HeroCard")]
            MITHeroCard = 4,
            [global::ProtoBuf.ProtoEnum(Name = @"MIT_Goods")]
            MITGoods = 5,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetMailInfoReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetMailInfoRes : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"data")]
        public global::System.Collections.Generic.List<MailData> Datas { get; } = new global::System.Collections.Generic.List<MailData>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ReadMailReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public ulong MailID { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ReadMailRes : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public ulong MailID { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public uint MailStatus { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"result")]
        public ReadMailResult Result { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public enum ReadMailResult
        {
            [global::ProtoBuf.ProtoEnum(Name = @"RMR_Sucess")]
            RMRSucess = 0,
            [global::ProtoBuf.ProtoEnum(Name = @"RMR_GetRewardErr")]
            RMRGetRewardErr = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"RMR_OtherFai")]
            RMROtherFai = 2,
            [global::ProtoBuf.ProtoEnum(Name = @"RMR_AlreadyRead")]
            RMRAlreadyRead = 3,
            [global::ProtoBuf.ProtoEnum(Name = @"RMR_MailIDerror")]
            RMRMailIDerror = 4,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ReadAllMailReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ReadAllMailRes : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"readResult")]
        public global::System.Collections.Generic.List<ReadMailRes> readResults { get; } = new global::System.Collections.Generic.List<ReadMailRes>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class DeleteMailReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public ulong MailID { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class DeleteMailRes : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public ulong MailID { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public uint MailStatus { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class DeleteAllMailReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class DeleteAllMailRes : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"data")]
        public global::System.Collections.Generic.List<DeleteMailRes> Datas { get; } = new global::System.Collections.Generic.List<DeleteMailRes>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class NewMail : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"data")]
        public MailData Data { get; set; }

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
