// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: rechargecard.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace Msg
{

    [global::ProtoBuf.ProtoContract()]
    public partial class RechargeCardInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public long WeekCardBuyTime { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public long WeekCardGetRewardTime { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public long MonthCardBuyTime { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public long MonthCardGetRewardTime { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public long SeasonCardBuyTime { get; set; }

        [global::ProtoBuf.ProtoMember(6)]
        public long SeasonCardGetRewardTime { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetRechargeCardReward : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public RechargeCardType cardType { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetRechargeCardRewardRes : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public RechargeCardType cardType { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public GetRechargeCardResult resultCode { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public enum GetRechargeCardResult
        {
            [global::ProtoBuf.ProtoEnum(Name = @"GRCR_Success")]
            GRCRSuccess = 0,
            [global::ProtoBuf.ProtoEnum(Name = @"GRCR_AlreadyGet")]
            GRCRAlreadyGet = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"GRCR_NoCard")]
            GRCRNoCard = 2,
            [global::ProtoBuf.ProtoEnum(Name = @"GRCR_CfgErro")]
            GRCRCfgErro = 3,
            [global::ProtoBuf.ProtoEnum(Name = @"GRCR_OtherErro")]
            GRCROtherErro = 4,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class OpenRandStone : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int OpenCounts { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class OpenStoneData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int StoneId { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public int StoneCount { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class OpenRandStoneRes : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"stoneData")]
        public global::System.Collections.Generic.List<OpenStoneData> stoneDatas { get; } = new global::System.Collections.Generic.List<OpenStoneData>();

    }

    [global::ProtoBuf.ProtoContract()]
    public enum RechargeCardType
    {
        [global::ProtoBuf.ProtoEnum(Name = @"Week_Card")]
        WeekCard = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"Month_Card")]
        MonthCard = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"Season_Card")]
        SeasonCard = 2,
    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
