// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: shop.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace Msg
{

    [global::ProtoBuf.ProtoContract()]
    public partial class VipLevelUp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public uint VipLevel { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public ulong VipExp { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class BuyShopItemReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public ShopType bsType { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public uint BuyItemID { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"counts")]
        public uint Counts { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class BuyShopItemRes : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public ShopType stType { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public BuyShopItemResult bsiCode { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public uint BuyItemID { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public enum BuyShopItemResult
        {
            [global::ProtoBuf.ProtoEnum(Name = @"BSIR_Success")]
            BSIRSuccess = 0,
            [global::ProtoBuf.ProtoEnum(Name = @"BSIR_NoCurrency")]
            BSIRNoCurrency = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"BSIR_NoShopItem")]
            BSIRNoShopItem = 2,
            [global::ProtoBuf.ProtoEnum(Name = @"BSIR_BuyCountError")]
            BSIRBuyCountError = 3,
            [global::ProtoBuf.ProtoEnum(Name = @"BSIR_VipError")]
            BSIRVipError = 4,
            [global::ProtoBuf.ProtoEnum(Name = @"BSIR_TimeError")]
            BSIRTimeError = 5,
            [global::ProtoBuf.ProtoEnum(Name = @"BSIR_GetItemError")]
            BSIRGetItemError = 6,
            [global::ProtoBuf.ProtoEnum(Name = @"BSIR_OtherError")]
            BSIROtherError = 7,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class UnlockHeroCardReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public uint CardId { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class UnlockHeroCardRes : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public UnlockResulltCode resultCode { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public uint CardId { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public enum UnlockResulltCode
        {
            [global::ProtoBuf.ProtoEnum(Name = @"URC_Success")]
            URCSuccess = 0,
            [global::ProtoBuf.ProtoEnum(Name = @"URC_CardError")]
            URCCardError = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"URC_NoDiamond")]
            URCNoDiamond = 2,
            [global::ProtoBuf.ProtoEnum(Name = @"URC_AlreadyUnlock")]
            URCAlreadyUnlock = 3,
            [global::ProtoBuf.ProtoEnum(Name = @"URC_OtherError")]
            URCOtherError = 4,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RMBBuyGoodsResult : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"result")]
        public RMBResult Result { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue("")]
        public string RMBGoodsID { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3)]
        public uint VipExp { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public int DayRecharge { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public enum RMBResult
        {
            [global::ProtoBuf.ProtoEnum(Name = @"RMBR_Success")]
            RMBRSuccess = 0,
            [global::ProtoBuf.ProtoEnum(Name = @"RMBR_Fail")]
            RMBRFail = 1,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public enum ShopType
    {
        [global::ProtoBuf.ProtoEnum(Name = @"STB_ShopGoods")]
        STBShopGoods = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"STB_RechargeGoods")]
        STBRechargeGoods = 1,
    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
