// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: task.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace Msg
{

    [global::ProtoBuf.ProtoContract()]
    public partial class PlayerTaskInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public long DayModaoshi { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public long DayUseSpar { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"DayTask")]
        public global::System.Collections.Generic.List<TaskData> DayTasks { get; } = new global::System.Collections.Generic.List<TaskData>();

        [global::ProtoBuf.ProtoMember(4, Name = @"RechargeTaskCfg")]
        public global::System.Collections.Generic.List<RechargeDayTaskInfo> RechargeTaskCfgs { get; } = new global::System.Collections.Generic.List<RechargeDayTaskInfo>();

        [global::ProtoBuf.ProtoMember(5)]
        public HighlyproTaskInfo HighlyproInfo { get; set; }

        [global::ProtoBuf.ProtoMember(6)]
        public TaskData ModaoshiTask { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class TaskData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int TaskId { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public int TaskStatus { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetDayTaskReward : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int TaskId { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetDayTaskRewardRes : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int TaskId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"result")]
        public GetTaskRewardResult Result { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public enum GetTaskRewardResult
        {
            [global::ProtoBuf.ProtoEnum(Name = @"GTRR_Success")]
            GTRRSuccess = 0,
            [global::ProtoBuf.ProtoEnum(Name = @"GTRR_DisComplete")]
            GTRRDisComplete = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"GTRR_AlreadyGet")]
            GTRRAlreadyGet = 2,
            [global::ProtoBuf.ProtoEnum(Name = @"GTRR_OtherError")]
            GTRROtherError = 3,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RechargeDayTaskInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int Id { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue("")]
        public string Description { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3)]
        public int Tapy { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public long Quantity { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public int Reward { get; set; }

        [global::ProtoBuf.ProtoMember(6)]
        public int Amount { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetPlayerTaskInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class DayTaskChangeNotice : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"UpdateTaskCfg")]
        public global::System.Collections.Generic.List<RechargeDayTaskInfo> UpdateTaskCfgs { get; } = new global::System.Collections.Generic.List<RechargeDayTaskInfo>();

        [global::ProtoBuf.ProtoMember(2, Name = @"NewTaskCfg")]
        public global::System.Collections.Generic.List<RechargeDayTaskInfo> NewTaskCfgs { get; } = new global::System.Collections.Generic.List<RechargeDayTaskInfo>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class HighlyproTaskInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int HighlyproStatus { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"GetSpar", IsPacked = true)]
        public long[] GetSpars { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"task")]
        public global::System.Collections.Generic.List<TaskData> Tasks { get; } = new global::System.Collections.Generic.List<TaskData>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetTaskRewardReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int TaskId { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetTaskRewardRes : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int TaskId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"result")]
        public GetTaskRewardResult Result { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public enum GetTaskRewardResult
        {
            [global::ProtoBuf.ProtoEnum(Name = @"GTRR_Success")]
            GTRRSuccess = 0,
            [global::ProtoBuf.ProtoEnum(Name = @"GTRR_DisComplete")]
            GTRRDisComplete = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"GTRR_AlreadyGet")]
            GTRRAlreadyGet = 2,
            [global::ProtoBuf.ProtoEnum(Name = @"GTRR_TaskLock")]
            GTRRTaskLock = 3,
            [global::ProtoBuf.ProtoEnum(Name = @"GTRR_OtherError")]
            GTRROtherError = 4,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetAllTaskRewardReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int TaskType { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"TaskList", IsPacked = true)]
        public int[] TaskLists { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetAllTaskRewardRes : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int TaskType { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"TaskList", IsPacked = true)]
        public int[] TaskLists { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"SuccessTask", IsPacked = true)]
        public int[] SuccessTasks { get; set; }

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
