// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: activityduobao.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace Msg
{

    [global::ProtoBuf.ProtoContract()]
    public partial class GetDuobaoInfoReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetDuobaoInfoRes : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int DuobaoCounts { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public int DuobaoQuan { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public DuobaoTaskInfo DuobaoTasks { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public global::System.Collections.Generic.List<DuobaoPlayerInfo> RecordDatas { get; } = new global::System.Collections.Generic.List<DuobaoPlayerInfo>();

        [global::ProtoBuf.ProtoMember(5)]
        public EntityRewardCfg EntityCfg { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class DuobaoTaskInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public long SparUse { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public int LoginDay { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public int RechargeDay { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public long LoginTask { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public long RechargTask { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class DuobaoPlayerInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int PlayerId { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue("")]
        public string PlayerName { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3)]
        public int RewardId { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class EntityRewardCfg : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"UnlockCondition", IsPacked = true)]
        public int[] UnlockConditions { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetDuobaoTaskRewardReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int TaskId { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetDuobaoTaskRewardRes : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int TaskId { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public int Result { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class DuobaoTableReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int Counts { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class DuobaoTableRes : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int Result { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"RewardId", IsPacked = true)]
        public int[] RewardIds { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public int RecordId { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public long Spar { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"modaoshi")]
        public int Modaoshi { get; set; }

        [global::ProtoBuf.ProtoMember(6)]
        public int Diamond { get; set; }

        [global::ProtoBuf.ProtoMember(7)]
        public int Stone { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetOwnDuobaoRecordReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetOwnDuobaoRecordRes : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public global::System.Collections.Generic.List<DuobaoRecordData> Records { get; } = new global::System.Collections.Generic.List<DuobaoRecordData>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class DuobaoRecordData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int RewardId { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public long RecordTime { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public int TableId { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public int RewardStatus { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class NoticePlayerEMS : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int TableId { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public int ReWardId { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PlayerEMSReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        [global::System.ComponentModel.DefaultValue("")]
        public string Name { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue("")]
        public string PhoneNumber { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3)]
        [global::System.ComponentModel.DefaultValue("")]
        public string Address { get; set; } = "";

        [global::ProtoBuf.ProtoMember(4)]
        public int RewardId { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public int TableId { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PlayerEMSRes : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int Result { get; set; }

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
