// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: activitycrusadedragon.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace Msg
{

    [global::ProtoBuf.ProtoContract()]
    public partial class GetCrusadeDragonActivityInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetCrusadeDragonActivityInfoRes : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public long AllHurt { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public long OwnHurt { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public int FreeCtusadeCounts { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"CrusadeRank")]
        public global::System.Collections.Generic.List<PlayerRankInfo> CrusadeRanks { get; } = new global::System.Collections.Generic.List<PlayerRankInfo>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class CrusadeDragonReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int ActType { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class CrusadeDragonRes : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int Result { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public long Hurt { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"RewardList", IsPacked = true)]
        public int[] RewardLists { get; set; }

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
