// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: activityegg.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace Msg
{

    [global::ProtoBuf.ProtoContract()]
    public partial class GetActivityEggInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetActivityEggInfoRes : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int ActivityStatus { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public long EndTime { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public long EggPoints { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"MsgList")]
        public global::System.Collections.Generic.List<EggbroadcastMsg> MsgLists { get; } = new global::System.Collections.Generic.List<EggbroadcastMsg>();

        [global::ProtoBuf.ProtoMember(5)]
        public long ModaoshiEggHitCounts { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class HitEggReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int EggTypeId { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class HitEggRes : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int Result { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public int EggTypeId { get; set; }

        [global::ProtoBuf.ProtoMember(3, IsPacked = true)]
        public int[] Rewards { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ActivityEggFresh : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int ActivityStatus { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class EggbroadcastMsg : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int PlayerId { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue("")]
        public string PlayerName { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3)]
        public int PlayerVip { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public int HitEggID { get; set; }

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
