// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: challenge.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace Msg
{

    [global::ProtoBuf.ProtoContract()]
    public partial class DayChallengeInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int DayPassLv { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public int DayPassLvGif { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetDayChallengeReward : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetDayChallengeRewardRes : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"result")]
        public ChallengeResultCode Result { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public enum ChallengeResultCode
        {
            [global::ProtoBuf.ProtoEnum(Name = @"CRC_Success")]
            CRCSuccess = 0,
            [global::ProtoBuf.ProtoEnum(Name = @"CRC_DisComplete")]
            CRCDisComplete = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"CRC_AlreadyGet")]
            CRCAlreadyGet = 2,
            [global::ProtoBuf.ProtoEnum(Name = @"CRC_Locked")]
            CRCLocked = 3,
            [global::ProtoBuf.ProtoEnum(Name = @"CRC_OtherError")]
            CRCOtherError = 4,
        }

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
