// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: modaoshi.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace Msg
{

    [global::ProtoBuf.ProtoContract()]
    public partial class ModaoshiGoodsInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public long ModaoshiID { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public long LastBuyTime { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public int BuyCount { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetModaoshiInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ModaoshiInfoRes : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"modaoshiGoodsInfo")]
        public global::System.Collections.Generic.List<ModaoshiGoodsInfo> modaoshiGoodsInfoes { get; } = new global::System.Collections.Generic.List<ModaoshiGoodsInfo>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class BindAliPayReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public BindAliPayType bindType { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue("")]
        public string AliPayInfo { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3)]
        [global::System.ComponentModel.DefaultValue("")]
        public string AliRealName { get; set; } = "";

        [global::ProtoBuf.ProtoContract()]
        public enum BindAliPayType
        {
            [global::ProtoBuf.ProtoEnum(Name = @"BAT_ALIPAY_USER_ID")]
            BatAlipayUserId = 0,
            [global::ProtoBuf.ProtoEnum(Name = @"BAT_ALIPAY_LOGON_ID")]
            BatAlipayLogonId = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"BAT_ALIPAY_OPEN_ID")]
            BatAlipayOpenId = 2,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class BindAliPayRes : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"result")]
        public BindAliPayResult Result { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"index")]
        public uint Index { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public enum BindAliPayResult
        {
            [global::ProtoBuf.ProtoEnum(Name = @"BAPR_Success")]
            BAPRSuccess = 0,
            [global::ProtoBuf.ProtoEnum(Name = @"BAPR_MaxCounts")]
            BAPRMaxCounts = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"BAPR_OtherError")]
            BAPROtherError = 2,
            [global::ProtoBuf.ProtoEnum(Name = @"BAPR_AlreadyBind")]
            BAPRAlreadyBind = 3,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetModaoshiToAliPayReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public ulong ModaoshiGoodsID { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetModaoshiToAliPayRes : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"result")]
        public GetAliPayModaoshiResult Result { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public ulong ModaoshiGoodsID { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public enum GetAliPayModaoshiResult
        {
            [global::ProtoBuf.ProtoEnum(Name = @"GAHR_Success")]
            GAHRSuccess = 0,
            [global::ProtoBuf.ProtoEnum(Name = @"GAHR_NoModaoshi")]
            GAHRNoModaoshi = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"GAHR_NoTimes")]
            GAHRNoTimes = 2,
            [global::ProtoBuf.ProtoEnum(Name = @"GAHR_VipError")]
            GAHRVipError = 3,
            [global::ProtoBuf.ProtoEnum(Name = @"GAHR_NoAliPay")]
            GAHRNoAliPay = 4,
            [global::ProtoBuf.ProtoEnum(Name = @"GAHR_NoGoods")]
            GAHRNoGoods = 5,
            [global::ProtoBuf.ProtoEnum(Name = @"GAHR_OtherError")]
            GAHROtherError = 6,
        }

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
