// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: newrank.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace Msg
{

    [global::ProtoBuf.ProtoContract()]
    public partial class GetPlayerRankInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetPlayerRankInfoRes : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"DayRank1")]
        public global::System.Collections.Generic.List<PlayerRankInfo> DayRank1s { get; } = new global::System.Collections.Generic.List<PlayerRankInfo>();

        [global::ProtoBuf.ProtoMember(2, Name = @"DayRank2")]
        public global::System.Collections.Generic.List<PlayerRankInfo> DayRank2s { get; } = new global::System.Collections.Generic.List<PlayerRankInfo>();

        [global::ProtoBuf.ProtoMember(3, Name = @"WeekRank1")]
        public global::System.Collections.Generic.List<PlayerRankInfo> WeekRank1s { get; } = new global::System.Collections.Generic.List<PlayerRankInfo>();

        [global::ProtoBuf.ProtoMember(4, Name = @"WeekRank2")]
        public global::System.Collections.Generic.List<PlayerRankInfo> WeekRank2s { get; } = new global::System.Collections.Generic.List<PlayerRankInfo>();

        [global::ProtoBuf.ProtoMember(5)]
        public RankPoolInfo OtherInfo { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RankPoolInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public long DayDrop1Pool { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public long DayDrop2Pool { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public long WeekDrop1Pool { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public long WeekDrop2Pool { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public long PlayerDayDrop1 { get; set; }

        [global::ProtoBuf.ProtoMember(6)]
        public long PlayerDayDrop2 { get; set; }

        [global::ProtoBuf.ProtoMember(7)]
        public long PlayerWeekDrop1 { get; set; }

        [global::ProtoBuf.ProtoMember(8)]
        public long PlayerWeekDrop2 { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PlayerRankInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int PlayerID { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue("")]
        public string PlayeName { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3)]
        public int PlayerHead { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public int PlayerVip { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public int RankType { get; set; }

        [global::ProtoBuf.ProtoMember(6)]
        public int PlayerRank { get; set; }

        [global::ProtoBuf.ProtoMember(7)]
        public long PlayerRankNumber { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PlayerRankRefresh : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetRankMatchInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetRankMatchInfoRes : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"CountsRank")]
        public global::System.Collections.Generic.List<PlayerRankInfo> CountsRanks { get; } = new global::System.Collections.Generic.List<PlayerRankInfo>();

        [global::ProtoBuf.ProtoMember(2, Name = @"ModaoshiRank")]
        public global::System.Collections.Generic.List<PlayerRankInfo> ModaoshiRanks { get; } = new global::System.Collections.Generic.List<PlayerRankInfo>();

        [global::ProtoBuf.ProtoMember(3)]
        public int GetCounts { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public long GetModaoshi { get; set; }

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
