// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: rechargeactivity.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace Msg
{

    [global::ProtoBuf.ProtoContract()]
    public partial class GetRechargeActivityReward : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public uint ActivityId { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetRechargeActivityRewardRes : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public uint Result { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public uint ActivityId { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PlayerRechargeActivityInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int ActivityId { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public int ActivityStatus { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public long GetTime { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetRechargeActivityInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetRechargeActivityInfoRes : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int ActivityStatus { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public long ActivityEndTime { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public long StartTime { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public int RechargeCounts { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"PlayerInfo")]
        public global::System.Collections.Generic.List<PlayerRechargeActivityInfo> PlayerInfoes { get; } = new global::System.Collections.Generic.List<PlayerRechargeActivityInfo>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RechargeActivityFresh : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
