// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: vipactivity.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace Msg
{

    [global::ProtoBuf.ProtoContract()]
    public partial class VipActivityInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public long StartTime { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public long EndTime { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public global::System.Collections.Generic.List<VipActivityData> Datas { get; } = new global::System.Collections.Generic.List<VipActivityData>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class VipActivityData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int ActivityID { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public int GetCounts { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PlayerVipActivityInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int ActivityId { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public int ActivityStatus { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public long GetTime { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetVipActivityInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetVipActivityInfoRes : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int ActivityStatus { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public VipActivityInfo ActivityInfo { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"PlayerInfo")]
        public global::System.Collections.Generic.List<PlayerVipActivityInfo> PlayerInfoes { get; } = new global::System.Collections.Generic.List<PlayerVipActivityInfo>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class VipActivityReward : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int RewardId { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public int RewardCounts { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class VipActivityCfg : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int ActivityId { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public int ActivityVip { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public int ActivityNumber { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"Reward")]
        public global::System.Collections.Generic.List<VipActivityReward> Rewards { get; } = new global::System.Collections.Generic.List<VipActivityReward>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetVipActivityCfg : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetVipActivityCfgRes : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int Result { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"ActivityCfg")]
        public global::System.Collections.Generic.List<VipActivityCfg> ActivityCfgs { get; } = new global::System.Collections.Generic.List<VipActivityCfg>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetVipActivityReward : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public uint ActivityId { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetVipActivityRewardRes : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public uint Result { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public uint ActivityId { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class VipActivityEndFresh : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class EquipRewardInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int Pos1Reward { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public int Pos2Reward { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public int Pos3Reward { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public int Pos4Reward { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public int Pos5Reward { get; set; }

        [global::ProtoBuf.ProtoMember(6)]
        public int Pos6Reward { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetEquipRewardInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetEquipRewardInfoRes : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public EquipRewardInfo RewardInfo { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetEquipLeveUpReward : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int EquipPos { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetEquipLeveUpRewardRes : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int RewardResult { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public int EquipPos { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public int RewardInfo { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetKillBossActivityInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PlayerKillBossActivityInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int BossScene { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public int KillCounts { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public long GetReWardTime { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public int BeforeKill { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class KillBossActivityInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"Info")]
        public global::System.Collections.Generic.List<PlayerKillBossActivityInfo> Infoes { get; } = new global::System.Collections.Generic.List<PlayerKillBossActivityInfo>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetKillBossReward : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int BossScene { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetKillBossRewardRes : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int Result { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public int RewardNumber { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public int BossScene { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetLongwangActivityInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class LongwangActivityInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public long SparPool { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public int Gongxun { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"LongwangRank")]
        public global::System.Collections.Generic.List<RankInfo> LongwangRanks { get; } = new global::System.Collections.Generic.List<RankInfo>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class LongwangActivityFresh : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
