
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public partial class SoundsConfig
{
    private readonly System.Collections.Generic.Dictionary<string, Sounds> _dataMap;
    private readonly System.Collections.Generic.List<Sounds> _dataList;
    
    public SoundsConfig(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<string, Sounds>();
        _dataList = new System.Collections.Generic.List<Sounds>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            Sounds _v;
            _v = Sounds.DeserializeSounds(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<string, Sounds> DataMap => _dataMap;
    public System.Collections.Generic.List<Sounds> DataList => _dataList;

    public Sounds GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Sounds Get(string key) => _dataMap[key];
    public Sounds this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

