
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public partial class HorseConfig
{
    private readonly System.Collections.Generic.Dictionary<int, Horse> _dataMap;
    private readonly System.Collections.Generic.List<Horse> _dataList;
    
    public HorseConfig(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Horse>();
        _dataList = new System.Collections.Generic.List<Horse>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            Horse _v;
            _v = Horse.DeserializeHorse(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Horse> DataMap => _dataMap;
    public System.Collections.Generic.List<Horse> DataList => _dataList;

    public Horse GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Horse Get(int key) => _dataMap[key];
    public Horse this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

