
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class Horse : Luban.BeanBase
{
    public Horse(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Icon = _buf.ReadString();
        Name = _buf.ReadString();
    }

    public static Horse DeserializeHorse(ByteBuf _buf)
    {
        return new Horse(_buf);
    }

    /// <summary>
    /// 这是id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 名字
    /// </summary>
    public readonly string Icon;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string Name;
   
    public const int __ID__ = 69913533;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Icon:" + Icon + ","
        + "Name:" + Name + ","
        + "}";
    }
}

}
