
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class Language : Luban.BeanBase
{
    public Language(ByteBuf _buf) 
    {
        Id = _buf.ReadString();
        Chinese = _buf.ReadString();
    }

    public static Language DeserializeLanguage(ByteBuf _buf)
    {
        return new Language(_buf);
    }

    /// <summary>
    /// 这是id
    /// </summary>
    public readonly string Id;
    /// <summary>
    /// 中文
    /// </summary>
    public readonly string Chinese;
   
    public const int __ID__ = -1548945544;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Chinese:" + Chinese + ","
        + "}";
    }
}

}
