
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class ActiveTask : Luban.BeanBase
{
    public ActiveTask(JSONNode _buf) 
    {
        { if(!_buf["Id"].IsNumber) { throw new SerializationException(); }  Id = _buf["Id"]; }
        { if(!_buf["TaskDescription"].IsString) { throw new SerializationException(); }  TaskDescription = _buf["TaskDescription"]; }
        { if(!_buf["NumberOfTasks"].IsNumber) { throw new SerializationException(); }  NumberOfTasks = _buf["NumberOfTasks"]; }
        { var __json0 = _buf["Price"]; if(!__json0.IsArray) { throw new SerializationException(); } Price = new System.Collections.Generic.List<ItemExchange>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { ItemExchange __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = ItemExchange.DeserializeItemExchange(__e0);  }  Price.Add(__v0); }   }
    }

    public static ActiveTask DeserializeActiveTask(JSONNode _buf)
    {
        return new ActiveTask(_buf);
    }

    /// <summary>
    /// 任务id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 任务描述
    /// </summary>
    public readonly string TaskDescription;
    /// <summary>
    /// 任务数量
    /// </summary>
    public readonly int NumberOfTasks;
    /// <summary>
    /// 任务奖励
    /// </summary>
    public readonly System.Collections.Generic.List<ItemExchange> Price;
   
    public const int __ID__ = -257551925;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        foreach (var _e in Price) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "TaskDescription:" + TaskDescription + ","
        + "NumberOfTasks:" + NumberOfTasks + ","
        + "Price:" + Luban.StringUtil.CollectionToString(Price) + ","
        + "}";
    }
}

}
