
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class AI : Luban.BeanBase
{
    public AI(JSONNode _buf) 
    {
        { if(!_buf["Id"].IsNumber) { throw new SerializationException(); }  Id = _buf["Id"]; }
        { if(!_buf["Name"].IsString) { throw new SerializationException(); }  Name = _buf["Name"]; }
        { if(!_buf["Type"].IsNumber) { throw new SerializationException(); }  Type = _buf["Type"]; }
        { if(!_buf["Codex"].IsNumber) { throw new SerializationException(); }  Codex = _buf["Codex"]; }
        { if(!_buf["Hp"].IsNumber) { throw new SerializationException(); }  Hp = _buf["Hp"]; }
        { if(!_buf["MoveSpeed"].IsNumber) { throw new SerializationException(); }  MoveSpeed = _buf["MoveSpeed"]; }
        { if(!_buf["Exp"].IsNumber) { throw new SerializationException(); }  Exp = _buf["Exp"]; }
        { if(!_buf["Att"].IsNumber) { throw new SerializationException(); }  Att = _buf["Att"]; }
        { var __json0 = _buf["Magnification"]; if(!__json0.IsArray) { throw new SerializationException(); } Magnification = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  Magnification.Add(__v0); }   }
        { if(!_buf["Probability"].IsNumber) { throw new SerializationException(); }  Probability = _buf["Probability"]; }
        { if(!_buf["Weight"].IsNumber) { throw new SerializationException(); }  Weight = _buf["Weight"]; }
        { if(!_buf["Scale"].IsNumber) { throw new SerializationException(); }  Scale = _buf["Scale"]; }
        { if(!_buf["ChanceExp"].IsNumber) { throw new SerializationException(); }  ChanceExp = _buf["ChanceExp"]; }
        { if(!_buf["Php"].IsNumber) { throw new SerializationException(); }  Php = _buf["Php"]; }
    }

    public static AI DeserializeAI(JSONNode _buf)
    {
        return new AI(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 名字
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 掉落类型
    /// </summary>
    public readonly int Type;
    /// <summary>
    /// 倍率（图鉴显示）
    /// </summary>
    public readonly int Codex;
    /// <summary>
    /// 基础生命
    /// </summary>
    public readonly int Hp;
    /// <summary>
    /// 移动速度
    /// </summary>
    public readonly float MoveSpeed;
    /// <summary>
    /// 经验值
    /// </summary>
    public readonly int Exp;
    /// <summary>
    /// 攻击力
    /// </summary>
    public readonly int Att;
    /// <summary>
    /// m值加成倍率
    /// </summary>
    public readonly System.Collections.Generic.List<int> Magnification;
    /// <summary>
    /// 概率/100
    /// </summary>
    public readonly int Probability;
    /// <summary>
    /// 体重
    /// </summary>
    public readonly float Weight;
    /// <summary>
    /// 缩放
    /// </summary>
    public readonly float Scale;
    /// <summary>
    /// 掉落经验概率
    /// </summary>
    public readonly int ChanceExp;
    /// <summary>
    /// 基础生命
    /// </summary>
    public readonly int Php;
   
    public const int __ID__ = 2088;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
        
        
        
        
        
        
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Name:" + Name + ","
        + "Type:" + Type + ","
        + "Codex:" + Codex + ","
        + "Hp:" + Hp + ","
        + "MoveSpeed:" + MoveSpeed + ","
        + "Exp:" + Exp + ","
        + "Att:" + Att + ","
        + "Magnification:" + Luban.StringUtil.CollectionToString(Magnification) + ","
        + "Probability:" + Probability + ","
        + "Weight:" + Weight + ","
        + "Scale:" + Scale + ","
        + "ChanceExp:" + ChanceExp + ","
        + "Php:" + Php + ","
        + "}";
    }
}

}
