
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class Beginner : Luban.BeanBase
{
    public Beginner(JSONNode _buf) 
    {
        { if(!_buf["Id"].IsNumber) { throw new SerializationException(); }  Id = _buf["Id"]; }
        { if(!_buf["Win"].IsNumber) { throw new SerializationException(); }  Win = _buf["Win"]; }
        { if(!_buf["Protectionmax"].IsNumber) { throw new SerializationException(); }  Protectionmax = _buf["Protectionmax"]; }
        { if(!_buf["Protectionmin"].IsNumber) { throw new SerializationException(); }  Protectionmin = _buf["Protectionmin"]; }
        { if(!_buf["Buffmax"].IsNumber) { throw new SerializationException(); }  Buffmax = _buf["Buffmax"]; }
        { if(!_buf["Buffmin"].IsNumber) { throw new SerializationException(); }  Buffmin = _buf["Buffmin"]; }
        { if(!_buf["Protectionnum"].IsNumber) { throw new SerializationException(); }  Protectionnum = _buf["Protectionnum"]; }
    }

    public static Beginner DeserializeBeginner(JSONNode _buf)
    {
        return new Beginner(_buf);
    }

    /// <summary>
    /// 策略id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 玩家赢取金币数量
    /// </summary>
    public readonly int Win;
    /// <summary>
    /// 保护最大值
    /// </summary>
    public readonly int Protectionmax;
    /// <summary>
    /// 保护最小值
    /// </summary>
    public readonly int Protectionmin;
    /// <summary>
    /// BUFF最大值/1000
    /// </summary>
    public readonly int Buffmax;
    /// <summary>
    /// BUFF最小值/1000
    /// </summary>
    public readonly int Buffmin;
    /// <summary>
    /// 保护流水值
    /// </summary>
    public readonly int Protectionnum;
   
    public const int __ID__ = 1554081906;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Win:" + Win + ","
        + "Protectionmax:" + Protectionmax + ","
        + "Protectionmin:" + Protectionmin + ","
        + "Buffmax:" + Buffmax + ","
        + "Buffmin:" + Buffmin + ","
        + "Protectionnum:" + Protectionnum + ","
        + "}";
    }
}

}
