
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class BossReward : Luban.BeanBase
{
    public BossReward(JSONNode _buf) 
    {
        { if(!_buf["Id"].IsNumber) { throw new SerializationException(); }  Id = _buf["Id"]; }
        { if(!_buf["Reward"].IsNumber) { throw new SerializationException(); }  Reward = _buf["Reward"]; }
        { if(!_buf["Number"].IsNumber) { throw new SerializationException(); }  Number = _buf["Number"]; }
        { if(!_buf["Extra"].IsNumber) { throw new SerializationException(); }  Extra = _buf["Extra"]; }
        { if(!_buf["Tax"].IsNumber) { throw new SerializationException(); }  Tax = _buf["Tax"]; }
    }

    public static BossReward DeserializeBossReward(JSONNode _buf)
    {
        return new BossReward(_buf);
    }

    /// <summary>
    /// ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 悬赏奖励id
    /// </summary>
    public readonly int Reward;
    /// <summary>
    /// 击败1只boss增加的奖励数量
    /// </summary>
    public readonly int Number;
    /// <summary>
    /// 最大值倍率
    /// </summary>
    public readonly int Extra;
    /// <summary>
    /// 抽税/100000
    /// </summary>
    public readonly int Tax;
   
    public const int __ID__ = 1138969884;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Reward:" + Reward + ","
        + "Number:" + Number + ","
        + "Extra:" + Extra + ","
        + "Tax:" + Tax + ","
        + "}";
    }
}

}
