
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class BossRewardConfig
{
    private readonly System.Collections.Generic.Dictionary<int, BossReward> _dataMap;
    private readonly System.Collections.Generic.List<BossReward> _dataList;
    
    public BossRewardConfig(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, BossReward>();
        _dataList = new System.Collections.Generic.List<BossReward>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            BossReward _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = BossReward.DeserializeBossReward(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, BossReward> DataMap => _dataMap;
    public System.Collections.Generic.List<BossReward> DataList => _dataList;

    public BossReward GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public BossReward Get(int key) => _dataMap[key];
    public BossReward this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

