
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class BountyRanking : Luban.BeanBase
{
    public BountyRanking(JSONNode _buf) 
    {
        { if(!_buf["Id"].IsNumber) { throw new SerializationException(); }  Id = _buf["Id"]; }
        { if(!_buf["TimesList"].IsNumber) { throw new SerializationException(); }  TimesList = _buf["TimesList"]; }
        { if(!_buf["NumberList"].IsNumber) { throw new SerializationException(); }  NumberList = _buf["NumberList"]; }
    }

    public static BountyRanking DeserializeBountyRanking(JSONNode _buf)
    {
        return new BountyRanking(_buf);
    }

    /// <summary>
    /// 名次id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 次数榜(魔币)
    /// </summary>
    public readonly int TimesList;
    /// <summary>
    /// 数量榜单（魔导石）
    /// </summary>
    public readonly int NumberList;
   
    public const int __ID__ = -1109879573;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "TimesList:" + TimesList + ","
        + "NumberList:" + NumberList + ","
        + "}";
    }
}

}
