
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class BountyRankingConfig
{
    private readonly System.Collections.Generic.Dictionary<int, BountyRanking> _dataMap;
    private readonly System.Collections.Generic.List<BountyRanking> _dataList;
    
    public BountyRankingConfig(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, BountyRanking>();
        _dataList = new System.Collections.Generic.List<BountyRanking>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            BountyRanking _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = BountyRanking.DeserializeBountyRanking(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, BountyRanking> DataMap => _dataMap;
    public System.Collections.Generic.List<BountyRanking> DataList => _dataList;

    public BountyRanking GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public BountyRanking Get(int key) => _dataMap[key];
    public BountyRanking this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

