
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class CoPurPacks : Luban.BeanBase
{
    public CoPurPacks(JSONNode _buf) 
    {
        { if(!_buf["Id"].IsNumber) { throw new SerializationException(); }  Id = _buf["Id"]; }
        { if(!_buf["Reward"].IsNumber) { throw new SerializationException(); }  Reward = _buf["Reward"]; }
        { if(!_buf["Give"].IsNumber) { throw new SerializationException(); }  Give = _buf["Give"]; }
        { if(!_buf["Price"].IsNumber) { throw new SerializationException(); }  Price = _buf["Price"]; }
        { if(!_buf["Preferential"].IsString) { throw new SerializationException(); }  Preferential = _buf["Preferential"]; }
        { if(!_buf["Unlock"].IsNumber) { throw new SerializationException(); }  Unlock = _buf["Unlock"]; }
    }

    public static CoPurPacks DeserializeCoPurPacks(JSONNode _buf)
    {
        return new CoPurPacks(_buf);
    }

    /// <summary>
    /// 礼包id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 基础(魔币)
    /// </summary>
    public readonly int Reward;
    /// <summary>
    /// 赠送魔币
    /// </summary>
    public readonly int Give;
    /// <summary>
    /// 价格
    /// </summary>
    public readonly int Price;
    /// <summary>
    /// 百分比显示
    /// </summary>
    public readonly string Preferential;
    /// <summary>
    /// 超时解锁价格（魔导石）
    /// </summary>
    public readonly int Unlock;
   
    public const int __ID__ = -1550237927;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Reward:" + Reward + ","
        + "Give:" + Give + ","
        + "Price:" + Price + ","
        + "Preferential:" + Preferential + ","
        + "Unlock:" + Unlock + ","
        + "}";
    }
}

}
