
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class CorrectConfig
{
    private readonly System.Collections.Generic.Dictionary<int, Correct> _dataMap;
    private readonly System.Collections.Generic.List<Correct> _dataList;
    
    public CorrectConfig(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Correct>();
        _dataList = new System.Collections.Generic.List<Correct>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            Correct _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = Correct.DeserializeCorrect(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Correct> DataMap => _dataMap;
    public System.Collections.Generic.List<Correct> DataList => _dataList;

    public Correct GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Correct Get(int key) => _dataMap[key];
    public Correct this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

