
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class Correct : Luban.BeanBase
{
    public Correct(JSONNode _buf) 
    {
        { if(!_buf["Id"].IsNumber) { throw new SerializationException(); }  Id = _buf["Id"]; }
        { var __json0 = _buf["Rate"]; if(!__json0.IsArray) { throw new SerializationException(); } Rate = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  Rate.Add(__v0); }   }
        { var __json0 = _buf["FixProbability"]; if(!__json0.IsArray) { throw new SerializationException(); } FixProbability = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  FixProbability.Add(__v0); }   }
        { var __json0 = _buf["FixRange"]; if(!__json0.IsArray) { throw new SerializationException(); } FixRange = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  FixRange.Add(__v0); }   }
        { var __json0 = _buf["FixHitCount"]; if(!__json0.IsArray) { throw new SerializationException(); } FixHitCount = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  FixHitCount.Add(__v0); }   }
        { if(!_buf["FixMaybeProbability"].IsNumber) { throw new SerializationException(); }  FixMaybeProbability = _buf["FixMaybeProbability"]; }
        { if(!_buf["FixCycle"].IsNumber) { throw new SerializationException(); }  FixCycle = _buf["FixCycle"]; }
        { if(!_buf["Codex"].IsNumber) { throw new SerializationException(); }  Codex = _buf["Codex"]; }
    }

    public static Correct DeserializeCorrect(JSONNode _buf)
    {
        return new Correct(_buf);
    }

    /// <summary>
    /// 规则ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 正常概率
    /// </summary>
    public readonly System.Collections.Generic.List<int> Rate;
    /// <summary>
    /// 强制修正介入范围
    /// </summary>
    public readonly System.Collections.Generic.List<int> FixProbability;
    /// <summary>
    /// 强制修正系数范围
    /// </summary>
    public readonly System.Collections.Generic.List<int> FixRange;
    /// <summary>
    /// 修正周期（命中次数）
    /// </summary>
    public readonly System.Collections.Generic.List<int> FixHitCount;
    /// <summary>
    /// 概率修正介入的概率
    /// </summary>
    public readonly int FixMaybeProbability;
    /// <summary>
    /// 修正周期
    /// </summary>
    public readonly int FixCycle;
    /// <summary>
    /// 触发条件
    /// </summary>
    public readonly int Codex;
   
    public const int __ID__ = -1675149238;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Rate:" + Luban.StringUtil.CollectionToString(Rate) + ","
        + "FixProbability:" + Luban.StringUtil.CollectionToString(FixProbability) + ","
        + "FixRange:" + Luban.StringUtil.CollectionToString(FixRange) + ","
        + "FixHitCount:" + Luban.StringUtil.CollectionToString(FixHitCount) + ","
        + "FixMaybeProbability:" + FixMaybeProbability + ","
        + "FixCycle:" + FixCycle + ","
        + "Codex:" + Codex + ","
        + "}";
    }
}

}
