
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class DailyLogin : Luban.BeanBase
{
    public DailyLogin(JSONNode _buf) 
    {
        { if(!_buf["Id"].IsNumber) { throw new SerializationException(); }  Id = _buf["Id"]; }
        { if(!_buf["Type"].IsNumber) { throw new SerializationException(); }  Type = _buf["Type"]; }
        { if(!_buf["Reward"].IsNumber) { throw new SerializationException(); }  Reward = _buf["Reward"]; }
    }

    public static DailyLogin DeserializeDailyLogin(JSONNode _buf)
    {
        return new DailyLogin(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 类型
    /// </summary>
    public readonly int Type;
    /// <summary>
    /// 奖励数量
    /// </summary>
    public readonly int Reward;
   
    public const int __ID__ = -792075024;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Type:" + Type + ","
        + "Reward:" + Reward + ","
        + "}";
    }
}

}
