
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class DailyCheckIn : Luban.BeanBase
{
    public DailyCheckIn(JSONNode _buf) 
    {
        { if(!_buf["Id"].IsNumber) { throw new SerializationException(); }  Id = _buf["Id"]; }
        { if(!_buf["Type"].IsNumber) { throw new SerializationException(); }  Type = _buf["Type"]; }
        { if(!_buf["Days"].IsNumber) { throw new SerializationException(); }  Days = _buf["Days"]; }
        { if(!_buf["Reward"].IsNumber) { throw new SerializationException(); }  Reward = _buf["Reward"]; }
        { if(!_buf["Number"].IsNumber) { throw new SerializationException(); }  Number = _buf["Number"]; }
    }

    public static DailyCheckIn DeserializeDailyCheckIn(JSONNode _buf)
    {
        return new DailyCheckIn(_buf);
    }

    /// <summary>
    /// 这是id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 类型
    /// </summary>
    public readonly int Type;
    /// <summary>
    /// 天数
    /// </summary>
    public readonly int Days;
    /// <summary>
    /// 奖励内容
    /// </summary>
    public readonly int Reward;
    /// <summary>
    /// 奖励数量
    /// </summary>
    public readonly int Number;
   
    public const int __ID__ = -574915564;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Type:" + Type + ","
        + "Days:" + Days + ","
        + "Reward:" + Reward + ","
        + "Number:" + Number + ","
        + "}";
    }
}

}
