
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class DailyCheckInConfig
{
    private readonly System.Collections.Generic.Dictionary<int, DailyCheckIn> _dataMap;
    private readonly System.Collections.Generic.List<DailyCheckIn> _dataList;
    
    public DailyCheckInConfig(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, DailyCheckIn>();
        _dataList = new System.Collections.Generic.List<DailyCheckIn>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            DailyCheckIn _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = DailyCheckIn.DeserializeDailyCheckIn(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, DailyCheckIn> DataMap => _dataMap;
    public System.Collections.Generic.List<DailyCheckIn> DataList => _dataList;

    public DailyCheckIn GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public DailyCheckIn Get(int key) => _dataMap[key];
    public DailyCheckIn this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

