
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class DayTaskConfig
{
    private readonly System.Collections.Generic.Dictionary<int, Task> _dataMap;
    private readonly System.Collections.Generic.List<Task> _dataList;
    
    public DayTaskConfig(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Task>();
        _dataList = new System.Collections.Generic.List<Task>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            Task _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = Task.DeserializeTask(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Task> DataMap => _dataMap;
    public System.Collections.Generic.List<Task> DataList => _dataList;

    public Task GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Task Get(int key) => _dataMap[key];
    public Task this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

