
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class DragonTreasure : Luban.BeanBase
{
    public DragonTreasure(JSONNode _buf) 
    {
        { if(!_buf["Id"].IsNumber) { throw new SerializationException(); }  Id = _buf["Id"]; }
        { if(!_buf["Price"].IsNumber) { throw new SerializationException(); }  Price = _buf["Price"]; }
        { var __json0 = _buf["Reward"]; if(!__json0.IsArray) { throw new SerializationException(); } Reward = new System.Collections.Generic.List<ItemExchange>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { ItemExchange __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = ItemExchange.DeserializeItemExchange(__e0);  }  Reward.Add(__v0); }   }
        { if(!_buf["Number"].IsNumber) { throw new SerializationException(); }  Number = _buf["Number"]; }
    }

    public static DragonTreasure DeserializeDragonTreasure(JSONNode _buf)
    {
        return new DragonTreasure(_buf);
    }

    /// <summary>
    /// 商品ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 价格
    /// </summary>
    public readonly int Price;
    /// <summary>
    /// 礼包内容奖励
    /// </summary>
    public readonly System.Collections.Generic.List<ItemExchange> Reward;
    /// <summary>
    /// 注入奖池数量/魔币
    /// </summary>
    public readonly int Number;
   
    public const int __ID__ = -14332414;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        foreach (var _e in Reward) { _e?.ResolveRef(tables); }
        
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Price:" + Price + ","
        + "Reward:" + Luban.StringUtil.CollectionToString(Reward) + ","
        + "Number:" + Number + ","
        + "}";
    }
}

}
