
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class EggPriceConfig
{
    private readonly System.Collections.Generic.Dictionary<int, EggPrice> _dataMap;
    private readonly System.Collections.Generic.List<EggPrice> _dataList;
    
    public EggPriceConfig(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, EggPrice>();
        _dataList = new System.Collections.Generic.List<EggPrice>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            EggPrice _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = EggPrice.DeserializeEggPrice(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, EggPrice> DataMap => _dataMap;
    public System.Collections.Generic.List<EggPrice> DataList => _dataList;

    public EggPrice GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public EggPrice Get(int key) => _dataMap[key];
    public EggPrice this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

