
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class EggPrice : Luban.BeanBase
{
    public EggPrice(JSONNode _buf) 
    {
        { if(!_buf["Id"].IsNumber) { throw new SerializationException(); }  Id = _buf["Id"]; }
        { if(!_buf["Type"].IsNumber) { throw new SerializationException(); }  Type = _buf["Type"]; }
        { if(!_buf["Times"].IsNumber) { throw new SerializationException(); }  Times = _buf["Times"]; }
        { if(!_buf["Deplete"].IsNumber) { throw new SerializationException(); }  Deplete = _buf["Deplete"]; }
        { if(!_buf["Relevancy"].IsNumber) { throw new SerializationException(); }  Relevancy = _buf["Relevancy"]; }
        { if(!_buf["Class"].IsNumber) { throw new SerializationException(); }  Class = _buf["Class"]; }
        { if(!_buf["Give"].IsNumber) { throw new SerializationException(); }  Give = _buf["Give"]; }
    }

    public static EggPrice DeserializeEggPrice(JSONNode _buf)
    {
        return new EggPrice(_buf);
    }

    /// <summary>
    /// 行为id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 砸蛋类型
    /// </summary>
    public readonly int Type;
    /// <summary>
    /// 砸蛋次数
    /// </summary>
    public readonly int Times;
    /// <summary>
    /// 消耗道具数量
    /// </summary>
    public readonly int Deplete;
    /// <summary>
    /// 关联奖励池
    /// </summary>
    public readonly int Relevancy;
    /// <summary>
    /// 奖励种类
    /// </summary>
    public readonly int Class;
    /// <summary>
    /// 赠送材料数量
    /// </summary>
    public readonly int Give;
   
    public const int __ID__ = -55388060;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Type:" + Type + ","
        + "Times:" + Times + ","
        + "Deplete:" + Deplete + ","
        + "Relevancy:" + Relevancy + ","
        + "Class:" + Class + ","
        + "Give:" + Give + ","
        + "}";
    }
}

}
