
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class EggRewardsConfig
{
    private readonly System.Collections.Generic.Dictionary<int, EggRewards> _dataMap;
    private readonly System.Collections.Generic.List<EggRewards> _dataList;
    
    public EggRewardsConfig(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, EggRewards>();
        _dataList = new System.Collections.Generic.List<EggRewards>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            EggRewards _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = EggRewards.DeserializeEggRewards(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, EggRewards> DataMap => _dataMap;
    public System.Collections.Generic.List<EggRewards> DataList => _dataList;

    public EggRewards GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public EggRewards Get(int key) => _dataMap[key];
    public EggRewards this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

