
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class EndlessModeConfig
{
    private readonly System.Collections.Generic.Dictionary<int, EndlessMode> _dataMap;
    private readonly System.Collections.Generic.List<EndlessMode> _dataList;
    
    public EndlessModeConfig(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, EndlessMode>();
        _dataList = new System.Collections.Generic.List<EndlessMode>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            EndlessMode _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = EndlessMode.DeserializeEndlessMode(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, EndlessMode> DataMap => _dataMap;
    public System.Collections.Generic.List<EndlessMode> DataList => _dataList;

    public EndlessMode GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public EndlessMode Get(int key) => _dataMap[key];
    public EndlessMode this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

