
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class EndlessMode : Luban.BeanBase
{
    public EndlessMode(JSONNode _buf) 
    {
        { if(!_buf["Id"].IsNumber) { throw new SerializationException(); }  Id = _buf["Id"]; }
        { if(!_buf["Type"].IsNumber) { throw new SerializationException(); }  Type = _buf["Type"]; }
        { if(!_buf["Amount"].IsNumber) { throw new SerializationException(); }  Amount = _buf["Amount"]; }
        { if(!_buf["Speed"].IsNumber) { throw new SerializationException(); }  Speed = _buf["Speed"]; }
        { if(!_buf["Amountmax"].IsNumber) { throw new SerializationException(); }  Amountmax = _buf["Amountmax"]; }
    }

    public static EndlessMode DeserializeEndlessMode(JSONNode _buf)
    {
        return new EndlessMode(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 类型/怪物
    /// </summary>
    public readonly int Type;
    /// <summary>
    /// 刷新数量
    /// </summary>
    public readonly int Amount;
    /// <summary>
    /// 刷新速度
    /// </summary>
    public readonly int Speed;
    /// <summary>
    /// 上限
    /// </summary>
    public readonly int Amountmax;
   
    public const int __ID__ = -2139553641;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Type:" + Type + ","
        + "Amount:" + Amount + ","
        + "Speed:" + Speed + ","
        + "Amountmax:" + Amountmax + ","
        + "}";
    }
}

}
