
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class EnhancementPacksConfig
{
    private readonly System.Collections.Generic.Dictionary<int, EnhancementPacks> _dataMap;
    private readonly System.Collections.Generic.List<EnhancementPacks> _dataList;
    
    public EnhancementPacksConfig(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, EnhancementPacks>();
        _dataList = new System.Collections.Generic.List<EnhancementPacks>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            EnhancementPacks _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = EnhancementPacks.DeserializeEnhancementPacks(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, EnhancementPacks> DataMap => _dataMap;
    public System.Collections.Generic.List<EnhancementPacks> DataList => _dataList;

    public EnhancementPacks GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public EnhancementPacks Get(int key) => _dataMap[key];
    public EnhancementPacks this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

