
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class EquipmentLevelConfig
{
    private readonly System.Collections.Generic.Dictionary<int, EquipmentLevel> _dataMap;
    private readonly System.Collections.Generic.List<EquipmentLevel> _dataList;
    
    public EquipmentLevelConfig(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, EquipmentLevel>();
        _dataList = new System.Collections.Generic.List<EquipmentLevel>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            EquipmentLevel _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = EquipmentLevel.DeserializeEquipmentLevel(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, EquipmentLevel> DataMap => _dataMap;
    public System.Collections.Generic.List<EquipmentLevel> DataList => _dataList;

    public EquipmentLevel GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public EquipmentLevel Get(int key) => _dataMap[key];
    public EquipmentLevel this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

