
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class EquipmentLevel : Luban.BeanBase
{
    public EquipmentLevel(JSONNode _buf) 
    {
        { if(!_buf["Id"].IsNumber) { throw new SerializationException(); }  Id = _buf["Id"]; }
        { if(!_buf["Level"].IsNumber) { throw new SerializationException(); }  Level = _buf["Level"]; }
        { if(!_buf["Gold"].IsNumber) { throw new SerializationException(); }  Gold = _buf["Gold"]; }
        { if(!_buf["Material"].IsNumber) { throw new SerializationException(); }  Material = _buf["Material"]; }
        { if(!_buf["Quality"].IsNumber) { throw new SerializationException(); }  Quality = _buf["Quality"]; }
        { if(!_buf["Basis"].IsNumber) { throw new SerializationException(); }  Basis = _buf["Basis"]; }
        { if(!_buf["Bonus"].IsNumber) { throw new SerializationException(); }  Bonus = _buf["Bonus"]; }
    }

    public static EquipmentLevel DeserializeEquipmentLevel(JSONNode _buf)
    {
        return new EquipmentLevel(_buf);
    }

    /// <summary>
    /// ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 等级
    /// </summary>
    public readonly int Level;
    /// <summary>
    /// 升级消耗晶币
    /// </summary>
    public readonly int Gold;
    /// <summary>
    /// 升级消耗材料
    /// </summary>
    public readonly int Material;
    /// <summary>
    /// 品质
    /// </summary>
    public readonly int Quality;
    /// <summary>
    /// 基础属性
    /// </summary>
    public readonly int Basis;
    /// <summary>
    /// 词条属性百分比/1000
    /// </summary>
    public readonly int Bonus;
   
    public const int __ID__ = 1089788598;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Level:" + Level + ","
        + "Gold:" + Gold + ","
        + "Material:" + Material + ","
        + "Quality:" + Quality + ","
        + "Basis:" + Basis + ","
        + "Bonus:" + Bonus + ","
        + "}";
    }
}

}
