
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class Equipment : Luban.BeanBase
{
    public Equipment(JSONNode _buf) 
    {
        { if(!_buf["Id"].IsNumber) { throw new SerializationException(); }  Id = _buf["Id"]; }
        { if(!_buf["Name"].IsString) { throw new SerializationException(); }  Name = _buf["Name"]; }
        { if(!_buf["IconPath"].IsString) { throw new SerializationException(); }  IconPath = _buf["IconPath"]; }
        { if(!_buf["Attribute"].IsString) { throw new SerializationException(); }  Attribute = _buf["Attribute"]; }
        { if(!_buf["AttributeIcon"].IsString) { throw new SerializationException(); }  AttributeIcon = _buf["AttributeIcon"]; }
    }

    public static Equipment DeserializeEquipment(JSONNode _buf)
    {
        return new Equipment(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 装备名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 图片路径
    /// </summary>
    public readonly string IconPath;
    /// <summary>
    /// 武器属性
    /// </summary>
    public readonly string Attribute;
    /// <summary>
    /// 武器图标
    /// </summary>
    public readonly string AttributeIcon;
   
    public const int __ID__ = -1214642834;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Name:" + Name + ","
        + "IconPath:" + IconPath + ","
        + "Attribute:" + Attribute + ","
        + "AttributeIcon:" + AttributeIcon + ","
        + "}";
    }
}

}
