
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class ExchangeMissions : Luban.BeanBase
{
    public ExchangeMissions(JSONNode _buf) 
    {
        { if(!_buf["Id"].IsNumber) { throw new SerializationException(); }  Id = _buf["Id"]; }
        { if(!_buf["Txt"].IsString) { throw new SerializationException(); }  Txt = _buf["Txt"]; }
        { if(!_buf["Progress"].IsNumber) { throw new SerializationException(); }  Progress = _buf["Progress"]; }
        { var __json0 = _buf["Reward"]; if(!__json0.IsArray) { throw new SerializationException(); } Reward = new System.Collections.Generic.List<ItemExchange>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { ItemExchange __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = ItemExchange.DeserializeItemExchange(__e0);  }  Reward.Add(__v0); }   }
    }

    public static ExchangeMissions DeserializeExchangeMissions(JSONNode _buf)
    {
        return new ExchangeMissions(_buf);
    }

    /// <summary>
    /// 任务id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 任务描述
    /// </summary>
    public readonly string Txt;
    /// <summary>
    /// 任务进度
    /// </summary>
    public readonly int Progress;
    /// <summary>
    /// 任务奖励
    /// </summary>
    public readonly System.Collections.Generic.List<ItemExchange> Reward;
   
    public const int __ID__ = -1841884214;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        foreach (var _e in Reward) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Txt:" + Txt + ","
        + "Progress:" + Progress + ","
        + "Reward:" + Luban.StringUtil.CollectionToString(Reward) + ","
        + "}";
    }
}

}
