
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class Exterminate : Luban.BeanBase
{
    public Exterminate(JSONNode _buf) 
    {
        { if(!_buf["Id"].IsNumber) { throw new SerializationException(); }  Id = _buf["Id"]; }
        { if(!_buf["Multiple"].IsNumber) { throw new SerializationException(); }  Multiple = _buf["Multiple"]; }
        { if(!_buf["Reward"].IsNumber) { throw new SerializationException(); }  Reward = _buf["Reward"]; }
        { if(!_buf["Number"].IsNumber) { throw new SerializationException(); }  Number = _buf["Number"]; }
        { if(!_buf["Probability"].IsNumber) { throw new SerializationException(); }  Probability = _buf["Probability"]; }
    }

    public static Exterminate DeserializeExterminate(JSONNode _buf)
    {
        return new Exterminate(_buf);
    }

    /// <summary>
    /// 奖励id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 暴击倍数
    /// </summary>
    public readonly int Multiple;
    /// <summary>
    /// 奖励类型
    /// </summary>
    public readonly int Reward;
    /// <summary>
    /// 奖励数量
    /// </summary>
    public readonly int Number;
    /// <summary>
    /// 概率/100
    /// </summary>
    public readonly int Probability;
   
    public const int __ID__ = 493613806;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Multiple:" + Multiple + ","
        + "Reward:" + Reward + ","
        + "Number:" + Number + ","
        + "Probability:" + Probability + ","
        + "}";
    }
}

}
