
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class ExtraConfig
{
    private readonly System.Collections.Generic.Dictionary<int, Extra> _dataMap;
    private readonly System.Collections.Generic.List<Extra> _dataList;
    
    public ExtraConfig(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Extra>();
        _dataList = new System.Collections.Generic.List<Extra>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            Extra _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = Extra.DeserializeExtra(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Extra> DataMap => _dataMap;
    public System.Collections.Generic.List<Extra> DataList => _dataList;

    public Extra GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Extra Get(int key) => _dataMap[key];
    public Extra this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

