
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class FormationPack : Luban.BeanBase
{
    public FormationPack(JSONNode _buf) 
    {
        { if(!_buf["Id"].IsNumber) { throw new SerializationException(); }  Id = _buf["Id"]; }
        { if(!_buf["Name"].IsString) { throw new SerializationException(); }  Name = _buf["Name"]; }
        { var __json0 = _buf["Rewards"]; if(!__json0.IsArray) { throw new SerializationException(); } Rewards = new System.Collections.Generic.List<ItemExchange>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { ItemExchange __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = ItemExchange.DeserializeItemExchange(__e0);  }  Rewards.Add(__v0); }   }
        { if(!_buf["FormationLevel"].IsNumber) { throw new SerializationException(); }  FormationLevel = _buf["FormationLevel"]; }
        { if(!_buf["Price"].IsNumber) { throw new SerializationException(); }  Price = _buf["Price"]; }
    }

    public static FormationPack DeserializeFormationPack(JSONNode _buf)
    {
        return new FormationPack(_buf);
    }

    /// <summary>
    /// 礼包id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 礼包购买额外奖励
    /// </summary>
    public readonly System.Collections.Generic.List<ItemExchange> Rewards;
    /// <summary>
    /// 阵法解锁等级
    /// </summary>
    public readonly int FormationLevel;
    /// <summary>
    /// 支付价格
    /// </summary>
    public readonly int Price;
   
    public const int __ID__ = -1795568054;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        foreach (var _e in Rewards) { _e?.ResolveRef(tables); }
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Name:" + Name + ","
        + "Rewards:" + Luban.StringUtil.CollectionToString(Rewards) + ","
        + "FormationLevel:" + FormationLevel + ","
        + "Price:" + Price + ","
        + "}";
    }
}

}
