
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class FormationPackConfig
{
    private readonly System.Collections.Generic.Dictionary<int, FormationPack> _dataMap;
    private readonly System.Collections.Generic.List<FormationPack> _dataList;
    
    public FormationPackConfig(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, FormationPack>();
        _dataList = new System.Collections.Generic.List<FormationPack>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            FormationPack _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = FormationPack.DeserializeFormationPack(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, FormationPack> DataMap => _dataMap;
    public System.Collections.Generic.List<FormationPack> DataList => _dataList;

    public FormationPack GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public FormationPack Get(int key) => _dataMap[key];
    public FormationPack this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

