
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class FortunePackConfig
{
    private readonly System.Collections.Generic.Dictionary<int, FortunePack> _dataMap;
    private readonly System.Collections.Generic.List<FortunePack> _dataList;
    
    public FortunePackConfig(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, FortunePack>();
        _dataList = new System.Collections.Generic.List<FortunePack>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            FortunePack _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = FortunePack.DeserializeFortunePack(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, FortunePack> DataMap => _dataMap;
    public System.Collections.Generic.List<FortunePack> DataList => _dataList;

    public FortunePack GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public FortunePack Get(int key) => _dataMap[key];
    public FortunePack this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

