
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class FortunePack : Luban.BeanBase
{
    public FortunePack(JSONNode _buf) 
    {
        { if(!_buf["Id"].IsNumber) { throw new SerializationException(); }  Id = _buf["Id"]; }
        { if(!_buf["Name"].IsString) { throw new SerializationException(); }  Name = _buf["Name"]; }
        { var __json0 = _buf["Reward1"]; if(!__json0.IsArray) { throw new SerializationException(); } Reward1 = new System.Collections.Generic.List<ItemExchange>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { ItemExchange __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = ItemExchange.DeserializeItemExchange(__e0);  }  Reward1.Add(__v0); }   }
        { var __json0 = _buf["Reward2"]; if(!__json0.IsArray) { throw new SerializationException(); } Reward2 = new System.Collections.Generic.List<ItemExchange>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { ItemExchange __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = ItemExchange.DeserializeItemExchange(__e0);  }  Reward2.Add(__v0); }   }
        { if(!_buf["Price"].IsNumber) { throw new SerializationException(); }  Price = _buf["Price"]; }
    }

    public static FortunePack DeserializeFortunePack(JSONNode _buf)
    {
        return new FortunePack(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 礼包名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 道具奖励
    /// </summary>
    public readonly System.Collections.Generic.List<ItemExchange> Reward1;
    /// <summary>
    /// 英雄奖励
    /// </summary>
    public readonly System.Collections.Generic.List<ItemExchange> Reward2;
    /// <summary>
    /// 支付价格
    /// </summary>
    public readonly int Price;
   
    public const int __ID__ = -1450838566;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        foreach (var _e in Reward1) { _e?.ResolveRef(tables); }
        foreach (var _e in Reward2) { _e?.ResolveRef(tables); }
        
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Name:" + Name + ","
        + "Reward1:" + Luban.StringUtil.CollectionToString(Reward1) + ","
        + "Reward2:" + Luban.StringUtil.CollectionToString(Reward2) + ","
        + "Price:" + Price + ","
        + "}";
    }
}

}
