
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class GlobalConfig
{
    private readonly System.Collections.Generic.Dictionary<string, Global> _dataMap;
    private readonly System.Collections.Generic.List<Global> _dataList;
    
    public GlobalConfig(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<string, Global>();
        _dataList = new System.Collections.Generic.List<Global>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            Global _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = Global.DeserializeGlobal(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Key, _v);
        }
    }

    public System.Collections.Generic.Dictionary<string, Global> DataMap => _dataMap;
    public System.Collections.Generic.List<Global> DataList => _dataList;

    public Global GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Global Get(string key) => _dataMap[key];
    public Global this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

