
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class Global : Luban.BeanBase
{
    public Global(JSONNode _buf) 
    {
        { if(!_buf["Key"].IsString) { throw new SerializationException(); }  Key = _buf["Key"]; }
        { if(!_buf["Value"].IsString) { throw new SerializationException(); }  Value = _buf["Value"]; }
    }

    public static Global DeserializeGlobal(JSONNode _buf)
    {
        return new Global(_buf);
    }

    /// <summary>
    /// 礼包id
    /// </summary>
    public readonly string Key;
    /// <summary>
    /// 值
    /// </summary>
    public readonly string Value;
   
    public const int __ID__ = 2135814083;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "Key:" + Key + ","
        + "Value:" + Value + ","
        + "}";
    }
}

}
