
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class GreatGiftConfig
{
    private readonly System.Collections.Generic.Dictionary<int, GreatGift> _dataMap;
    private readonly System.Collections.Generic.List<GreatGift> _dataList;
    
    public GreatGiftConfig(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, GreatGift>();
        _dataList = new System.Collections.Generic.List<GreatGift>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            GreatGift _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = GreatGift.DeserializeGreatGift(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, GreatGift> DataMap => _dataMap;
    public System.Collections.Generic.List<GreatGift> DataList => _dataList;

    public GreatGift GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public GreatGift Get(int key) => _dataMap[key];
    public GreatGift this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

