
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class GreatGift : Luban.BeanBase
{
    public GreatGift(JSONNode _buf) 
    {
        { if(!_buf["Id"].IsNumber) { throw new SerializationException(); }  Id = _buf["Id"]; }
        { if(!_buf["Description"].IsString) { throw new SerializationException(); }  Description = _buf["Description"]; }
        { if(!_buf["Quantity"].IsNumber) { throw new SerializationException(); }  Quantity = _buf["Quantity"]; }
        { if(!_buf["Reward"].IsNumber) { throw new SerializationException(); }  Reward = _buf["Reward"]; }
        { if(!_buf["CalculatedValue"].IsNumber) { throw new SerializationException(); }  CalculatedValue = _buf["CalculatedValue"]; }
        { if(!_buf["TaskType"].IsNumber) { throw new SerializationException(); }  TaskType = _buf["TaskType"]; }
    }

    public static GreatGift DeserializeGreatGift(JSONNode _buf)
    {
        return new GreatGift(_buf);
    }

    /// <summary>
    /// 任务id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 任务描述
    /// </summary>
    public readonly string Description;
    /// <summary>
    /// 目标数量
    /// </summary>
    public readonly long Quantity;
    /// <summary>
    /// 奖励波动系数%
    /// </summary>
    public readonly int Reward;
    /// <summary>
    /// 奖励计算值
    /// </summary>
    public readonly long CalculatedValue;
    /// <summary>
    /// 任务类型
    /// </summary>
    public readonly int TaskType;
   
    public const int __ID__ = -333398723;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Description:" + Description + ","
        + "Quantity:" + Quantity + ","
        + "Reward:" + Reward + ","
        + "CalculatedValue:" + CalculatedValue + ","
        + "TaskType:" + TaskType + ","
        + "}";
    }
}

}
