
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class GuideConfig
{
    private readonly System.Collections.Generic.Dictionary<int, Guide> _dataMap;
    private readonly System.Collections.Generic.List<Guide> _dataList;
    
    public GuideConfig(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Guide>();
        _dataList = new System.Collections.Generic.List<Guide>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            Guide _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = Guide.DeserializeGuide(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Guide> DataMap => _dataMap;
    public System.Collections.Generic.List<Guide> DataList => _dataList;

    public Guide GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Guide Get(int key) => _dataMap[key];
    public Guide this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

