
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class Guide : Luban.BeanBase
{
    public Guide(JSONNode _buf) 
    {
        { if(!_buf["Id"].IsNumber) { throw new SerializationException(); }  Id = _buf["Id"]; }
        { if(!_buf["Name"].IsString) { throw new SerializationException(); }  Name = _buf["Name"]; }
        { if(!_buf["next"].IsNumber) { throw new SerializationException(); }  Next = _buf["next"]; }
        { if(!_buf["type"].IsNumber) { throw new SerializationException(); }  Type = _buf["type"]; }
        { if(!_buf["step"].IsNumber) { throw new SerializationException(); }  Step = _buf["step"]; }
        { if(!_buf["taskContent"].IsString) { throw new SerializationException(); }  TaskContent = _buf["taskContent"]; }
        { var __json0 = _buf["arrowPos"]; if(!__json0.IsArray) { throw new SerializationException(); } ArrowPos = new System.Collections.Generic.List<float>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { float __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  ArrowPos.Add(__v0); }   }
        { if(!_buf["isarrow"].IsNumber) { throw new SerializationException(); }  Isarrow = _buf["isarrow"]; }
        { if(!_buf["uiType"].IsNumber) { throw new SerializationException(); }  UiType = _buf["uiType"]; }
        { if(!_buf["arrowRota"].IsNumber) { throw new SerializationException(); }  ArrowRota = _buf["arrowRota"]; }
        { var __json0 = _buf["BgWightAndHeight"]; if(!__json0.IsArray) { throw new SerializationException(); } BgWightAndHeight = new System.Collections.Generic.List<float>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { float __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  BgWightAndHeight.Add(__v0); }   }
        { var __json0 = _buf["FontWightAndHeight"]; if(!__json0.IsArray) { throw new SerializationException(); } FontWightAndHeight = new System.Collections.Generic.List<float>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { float __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  FontWightAndHeight.Add(__v0); }   }
        { var __json0 = _buf["FontPos"]; if(!__json0.IsArray) { throw new SerializationException(); } FontPos = new System.Collections.Generic.List<float>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { float __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  FontPos.Add(__v0); }   }
        { if(!_buf["Sound"].IsString) { throw new SerializationException(); }  Sound = _buf["Sound"]; }
    }

    public static Guide DeserializeGuide(JSONNode _buf)
    {
        return new Guide(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 步骤描述
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 下一个引导id
    /// </summary>
    public readonly int Next;
    /// <summary>
    /// 大步骤
    /// </summary>
    public readonly int Type;
    /// <summary>
    /// 小步骤
    /// </summary>
    public readonly int Step;
    /// <summary>
    /// 妹子说话
    /// </summary>
    public readonly string TaskContent;
    /// <summary>
    /// 箭头位置
    /// </summary>
    public readonly System.Collections.Generic.List<float> ArrowPos;
    /// <summary>
    /// 是否有箭头
    /// </summary>
    public readonly int Isarrow;
    /// <summary>
    /// 打开对应界面
    /// </summary>
    public readonly int UiType;
    /// <summary>
    /// 箭头旋转位置
    /// </summary>
    public readonly int ArrowRota;
    /// <summary>
    /// 背景的长宽
    /// </summary>
    public readonly System.Collections.Generic.List<float> BgWightAndHeight;
    /// <summary>
    /// 字体的长宽
    /// </summary>
    public readonly System.Collections.Generic.List<float> FontWightAndHeight;
    /// <summary>
    /// 字体的位置
    /// </summary>
    public readonly System.Collections.Generic.List<float> FontPos;
    /// <summary>
    /// 音频
    /// </summary>
    public readonly string Sound;
   
    public const int __ID__ = 69159644;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
        
        
        
        
        
        
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Name:" + Name + ","
        + "next:" + Next + ","
        + "type:" + Type + ","
        + "step:" + Step + ","
        + "taskContent:" + TaskContent + ","
        + "arrowPos:" + Luban.StringUtil.CollectionToString(ArrowPos) + ","
        + "isarrow:" + Isarrow + ","
        + "uiType:" + UiType + ","
        + "arrowRota:" + ArrowRota + ","
        + "BgWightAndHeight:" + Luban.StringUtil.CollectionToString(BgWightAndHeight) + ","
        + "FontWightAndHeight:" + Luban.StringUtil.CollectionToString(FontWightAndHeight) + ","
        + "FontPos:" + Luban.StringUtil.CollectionToString(FontPos) + ","
        + "Sound:" + Sound + ","
        + "}";
    }
}

}
