
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class HeroHeadConfig
{
    private readonly System.Collections.Generic.Dictionary<int, HeroHead> _dataMap;
    private readonly System.Collections.Generic.List<HeroHead> _dataList;
    
    public HeroHeadConfig(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, HeroHead>();
        _dataList = new System.Collections.Generic.List<HeroHead>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            HeroHead _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = HeroHead.DeserializeHeroHead(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, HeroHead> DataMap => _dataMap;
    public System.Collections.Generic.List<HeroHead> DataList => _dataList;

    public HeroHead GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public HeroHead Get(int key) => _dataMap[key];
    public HeroHead this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

