
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class Hero : Luban.BeanBase
{
    public Hero(JSONNode _buf) 
    {
        { if(!_buf["Id"].IsNumber) { throw new SerializationException(); }  Id = _buf["Id"]; }
        { if(!_buf["Name"].IsString) { throw new SerializationException(); }  Name = _buf["Name"]; }
        { if(!_buf["Type"].IsNumber) { throw new SerializationException(); }  Type = _buf["Type"]; }
        { if(!_buf["Attribute"].IsNumber) { throw new SerializationException(); }  Attribute = _buf["Attribute"]; }
        { if(!_buf["Attack"].IsNumber) { throw new SerializationException(); }  Attack = _buf["Attack"]; }
        { if(!_buf["Unlock"].IsNumber) { throw new SerializationException(); }  Unlock = _buf["Unlock"]; }
        { if(!_buf["Price"].IsNumber) { throw new SerializationException(); }  Price = _buf["Price"]; }
    }

    public static Hero DeserializeHero(JSONNode _buf)
    {
        return new Hero(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 品质
    /// </summary>
    public readonly int Type;
    /// <summary>
    /// 属性
    /// </summary>
    public readonly int Attribute;
    /// <summary>
    /// 攻击
    /// </summary>
    public readonly int Attack;
    /// <summary>
    /// 解锁方式
    /// </summary>
    public readonly int Unlock;
    /// <summary>
    /// 价格
    /// </summary>
    public readonly int Price;
   
    public const int __ID__ = 2245658;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Name:" + Name + ","
        + "Type:" + Type + ","
        + "Attribute:" + Attribute + ","
        + "Attack:" + Attack + ","
        + "Unlock:" + Unlock + ","
        + "Price:" + Price + ","
        + "}";
    }
}

}
