
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class HighlyProfitable : Luban.BeanBase
{
    public HighlyProfitable(JSONNode _buf) 
    {
        { if(!_buf["Id"].IsNumber) { throw new SerializationException(); }  Id = _buf["Id"]; }
        { if(!_buf["Name"].IsString) { throw new SerializationException(); }  Name = _buf["Name"]; }
        { var __json0 = _buf["BaseRewards"]; if(!__json0.IsArray) { throw new SerializationException(); } BaseRewards = new System.Collections.Generic.List<ItemExchange>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { ItemExchange __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = ItemExchange.DeserializeItemExchange(__e0);  }  BaseRewards.Add(__v0); }   }
        { if(!_buf["ProgressLimit"].IsNumber) { throw new SerializationException(); }  ProgressLimit = _buf["ProgressLimit"]; }
        { if(!_buf["TasksNumber"].IsNumber) { throw new SerializationException(); }  TasksNumber = _buf["TasksNumber"]; }
        { if(!_buf["Price"].IsNumber) { throw new SerializationException(); }  Price = _buf["Price"]; }
    }

    public static HighlyProfitable DeserializeHighlyProfitable(JSONNode _buf)
    {
        return new HighlyProfitable(_buf);
    }

    /// <summary>
    /// 礼包id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 礼包购买基础奖励
    /// </summary>
    public readonly System.Collections.Generic.List<ItemExchange> BaseRewards;
    /// <summary>
    /// 任务进度奖励上限
    /// </summary>
    public readonly int ProgressLimit;
    /// <summary>
    /// 任务数量
    /// </summary>
    public readonly int TasksNumber;
    /// <summary>
    /// 支付价格
    /// </summary>
    public readonly int Price;
   
    public const int __ID__ = -435294771;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        foreach (var _e in BaseRewards) { _e?.ResolveRef(tables); }
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Name:" + Name + ","
        + "BaseRewards:" + Luban.StringUtil.CollectionToString(BaseRewards) + ","
        + "ProgressLimit:" + ProgressLimit + ","
        + "TasksNumber:" + TasksNumber + ","
        + "Price:" + Price + ","
        + "}";
    }
}

}
