
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class InventoryBuff : Luban.BeanBase
{
    public InventoryBuff(JSONNode _buf) 
    {
        { if(!_buf["Id"].IsNumber) { throw new SerializationException(); }  Id = _buf["Id"]; }
        { if(!_buf["UpPro"].IsNumber) { throw new SerializationException(); }  UpPro = _buf["UpPro"]; }
        { if(!_buf["DownPro"].IsNumber) { throw new SerializationException(); }  DownPro = _buf["DownPro"]; }
        { var __json0 = _buf["StartBuffUseCondition"]; if(!__json0.IsArray) { throw new SerializationException(); } StartBuffUseCondition = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  StartBuffUseCondition.Add(__v0); }   }
        { if(!_buf["StartBuffCondition"].IsNumber) { throw new SerializationException(); }  StartBuffCondition = _buf["StartBuffCondition"]; }
        { if(!_buf["NormalStartBuffCondition"].IsNumber) { throw new SerializationException(); }  NormalStartBuffCondition = _buf["NormalStartBuffCondition"]; }
        { if(!_buf["LowBuffCondition"].IsNumber) { throw new SerializationException(); }  LowBuffCondition = _buf["LowBuffCondition"]; }
        { if(!_buf["UpBuffCondition"].IsNumber) { throw new SerializationException(); }  UpBuffCondition = _buf["UpBuffCondition"]; }
        { var __json0 = _buf["EndUseCondition"]; if(!__json0.IsArray) { throw new SerializationException(); } EndUseCondition = new System.Collections.Generic.List<long>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { long __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  EndUseCondition.Add(__v0); }   }
        { var __json0 = _buf["EndProCondition"]; if(!__json0.IsArray) { throw new SerializationException(); } EndProCondition = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  EndProCondition.Add(__v0); }   }
        { var __json0 = _buf["BuffBullet"]; if(!__json0.IsArray) { throw new SerializationException(); } BuffBullet = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  BuffBullet.Add(__v0); }   }
        { var __json0 = _buf["FishPrice"]; if(!__json0.IsArray) { throw new SerializationException(); } FishPrice = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  FishPrice.Add(__v0); }   }
        { if(!_buf["NextSavePro"].IsNumber) { throw new SerializationException(); }  NextSavePro = _buf["NextSavePro"]; }
        { var __json0 = _buf["BossPrice"]; if(!__json0.IsArray) { throw new SerializationException(); } BossPrice = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  BossPrice.Add(__v0); }   }
    }

    public static InventoryBuff DeserializeInventoryBuff(JSONNode _buf)
    {
        return new InventoryBuff(_buf);
    }

    /// <summary>
    /// 场次id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 增益buff
    /// </summary>
    public readonly int UpPro;
    /// <summary>
    /// 减益buff
    /// </summary>
    public readonly int DownPro;
    /// <summary>
    /// buff生效使用条件
    /// </summary>
    public readonly System.Collections.Generic.List<int> StartBuffUseCondition;
    /// <summary>
    /// 第一次起始增益buff激活条件 rtp=总获得/总使用
    /// </summary>
    public readonly int StartBuffCondition;
    /// <summary>
    /// 循环后起始增益buff激活条件
    /// </summary>
    public readonly int NormalStartBuffCondition;
    /// <summary>
    /// 减益buff激活条件
    /// </summary>
    public readonly int LowBuffCondition;
    /// <summary>
    /// 增益buff激活条件
    /// </summary>
    public readonly int UpBuffCondition;
    /// <summary>
    /// 结束使用值
    /// </summary>
    public readonly System.Collections.Generic.List<long> EndUseCondition;
    /// <summary>
    /// 结束返奖率
    /// </summary>
    public readonly System.Collections.Generic.List<int> EndProCondition;
    /// <summary>
    /// 子弹区间
    /// </summary>
    public readonly System.Collections.Generic.List<int> BuffBullet;
    /// <summary>
    /// 生效倍率区间
    /// </summary>
    public readonly System.Collections.Generic.List<int> FishPrice;
    /// <summary>
    /// 新循环开始救人rtp
    /// </summary>
    public readonly int NextSavePro;
    /// <summary>
    /// 生效boss最大倍率
    /// </summary>
    public readonly System.Collections.Generic.List<int> BossPrice;
   
    public const int __ID__ = -726990929;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
        
        
        
        
        
        
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "UpPro:" + UpPro + ","
        + "DownPro:" + DownPro + ","
        + "StartBuffUseCondition:" + Luban.StringUtil.CollectionToString(StartBuffUseCondition) + ","
        + "StartBuffCondition:" + StartBuffCondition + ","
        + "NormalStartBuffCondition:" + NormalStartBuffCondition + ","
        + "LowBuffCondition:" + LowBuffCondition + ","
        + "UpBuffCondition:" + UpBuffCondition + ","
        + "EndUseCondition:" + Luban.StringUtil.CollectionToString(EndUseCondition) + ","
        + "EndProCondition:" + Luban.StringUtil.CollectionToString(EndProCondition) + ","
        + "BuffBullet:" + Luban.StringUtil.CollectionToString(BuffBullet) + ","
        + "FishPrice:" + Luban.StringUtil.CollectionToString(FishPrice) + ","
        + "NextSavePro:" + NextSavePro + ","
        + "BossPrice:" + Luban.StringUtil.CollectionToString(BossPrice) + ","
        + "}";
    }
}

}
