
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class ItemsConfig
{
    private readonly System.Collections.Generic.Dictionary<int, Items> _dataMap;
    private readonly System.Collections.Generic.List<Items> _dataList;
    
    public ItemsConfig(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Items>();
        _dataList = new System.Collections.Generic.List<Items>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            Items _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = Items.DeserializeItems(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Items> DataMap => _dataMap;
    public System.Collections.Generic.List<Items> DataList => _dataList;

    public Items GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Items Get(int key) => _dataMap[key];
    public Items this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

