
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class Items : Luban.BeanBase
{
    public Items(JSONNode _buf) 
    {
        { if(!_buf["Id"].IsNumber) { throw new SerializationException(); }  Id = _buf["Id"]; }
        { if(!_buf["Name"].IsString) { throw new SerializationException(); }  Name = _buf["Name"]; }
        { if(!_buf["Type"].IsNumber) { throw new SerializationException(); }  Type = _buf["Type"]; }
        { if(!_buf["Quality"].IsNumber) { throw new SerializationException(); }  Quality = _buf["Quality"]; }
        { if(!_buf["Txt"].IsString) { throw new SerializationException(); }  Txt = _buf["Txt"]; }
    }

    public static Items DeserializeItems(JSONNode _buf)
    {
        return new Items(_buf);
    }

    /// <summary>
    /// 道具id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 道具名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 道具类型
    /// </summary>
    public readonly int Type;
    /// <summary>
    /// 品质（框）
    /// </summary>
    public readonly int Quality;
    /// <summary>
    /// 道具描述
    /// </summary>
    public readonly string Txt;
   
    public const int __ID__ = 70973344;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Name:" + Name + ","
        + "Type:" + Type + ","
        + "Quality:" + Quality + ","
        + "Txt:" + Txt + ","
        + "}";
    }
}

}
