
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class Juhuasuan : Luban.BeanBase
{
    public Juhuasuan(JSONNode _buf) 
    {
        { if(!_buf["Id"].IsNumber) { throw new SerializationException(); }  Id = _buf["Id"]; }
        { if(!_buf["Name"].IsString) { throw new SerializationException(); }  Name = _buf["Name"]; }
        { var __json0 = _buf["BaseRewards"]; if(!__json0.IsArray) { throw new SerializationException(); } BaseRewards = new System.Collections.Generic.List<ItemExchange>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { ItemExchange __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = ItemExchange.DeserializeItemExchange(__e0);  }  BaseRewards.Add(__v0); }   }
        { var __json0 = _buf["FirstRewards"]; if(!__json0.IsArray) { throw new SerializationException(); } FirstRewards = new System.Collections.Generic.List<ItemExchange>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { ItemExchange __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = ItemExchange.DeserializeItemExchange(__e0);  }  FirstRewards.Add(__v0); }   }
        { var __json0 = _buf["SecondRewards"]; if(!__json0.IsArray) { throw new SerializationException(); } SecondRewards = new System.Collections.Generic.List<ItemExchange>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { ItemExchange __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = ItemExchange.DeserializeItemExchange(__e0);  }  SecondRewards.Add(__v0); }   }
        { if(!_buf["TimeInterval"].IsNumber) { throw new SerializationException(); }  TimeInterval = _buf["TimeInterval"]; }
        { var __json0 = _buf["ExtraRewards"]; if(!__json0.IsArray) { throw new SerializationException(); } ExtraRewards = new System.Collections.Generic.List<ItemExchange>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { ItemExchange __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = ItemExchange.DeserializeItemExchange(__e0);  }  ExtraRewards.Add(__v0); }   }
        { if(!_buf["OriginalPrice"].IsNumber) { throw new SerializationException(); }  OriginalPrice = _buf["OriginalPrice"]; }
        { if(!_buf["Price"].IsNumber) { throw new SerializationException(); }  Price = _buf["Price"]; }
    }

    public static Juhuasuan DeserializeJuhuasuan(JSONNode _buf)
    {
        return new Juhuasuan(_buf);
    }

    /// <summary>
    /// 礼包id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 礼包购买基础奖励
    /// </summary>
    public readonly System.Collections.Generic.List<ItemExchange> BaseRewards;
    /// <summary>
    /// 首次购买额外奖励
    /// </summary>
    public readonly System.Collections.Generic.List<ItemExchange> FirstRewards;
    /// <summary>
    /// 再次购买额外奖励
    /// </summary>
    public readonly System.Collections.Generic.List<ItemExchange> SecondRewards;
    /// <summary>
    /// 连续购买奖励间隔/秒
    /// </summary>
    public readonly int TimeInterval;
    /// <summary>
    /// 连续购买奖励
    /// </summary>
    public readonly System.Collections.Generic.List<ItemExchange> ExtraRewards;
    /// <summary>
    /// 原价
    /// </summary>
    public readonly int OriginalPrice;
    /// <summary>
    /// 商品价格&amp;支付
    /// </summary>
    public readonly int Price;
   
    public const int __ID__ = -1603429064;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        foreach (var _e in BaseRewards) { _e?.ResolveRef(tables); }
        foreach (var _e in FirstRewards) { _e?.ResolveRef(tables); }
        foreach (var _e in SecondRewards) { _e?.ResolveRef(tables); }
        
        foreach (var _e in ExtraRewards) { _e?.ResolveRef(tables); }
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Name:" + Name + ","
        + "BaseRewards:" + Luban.StringUtil.CollectionToString(BaseRewards) + ","
        + "FirstRewards:" + Luban.StringUtil.CollectionToString(FirstRewards) + ","
        + "SecondRewards:" + Luban.StringUtil.CollectionToString(SecondRewards) + ","
        + "TimeInterval:" + TimeInterval + ","
        + "ExtraRewards:" + Luban.StringUtil.CollectionToString(ExtraRewards) + ","
        + "OriginalPrice:" + OriginalPrice + ","
        + "Price:" + Price + ","
        + "}";
    }
}

}
