
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class JuhuasuanConfig
{
    private readonly System.Collections.Generic.Dictionary<int, Juhuasuan> _dataMap;
    private readonly System.Collections.Generic.List<Juhuasuan> _dataList;
    
    public JuhuasuanConfig(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Juhuasuan>();
        _dataList = new System.Collections.Generic.List<Juhuasuan>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            Juhuasuan _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = Juhuasuan.DeserializeJuhuasuan(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Juhuasuan> DataMap => _dataMap;
    public System.Collections.Generic.List<Juhuasuan> DataList => _dataList;

    public Juhuasuan GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Juhuasuan Get(int key) => _dataMap[key];
    public Juhuasuan this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

