
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class Leaderboard : Luban.BeanBase
{
    public Leaderboard(JSONNode _buf) 
    {
        { if(!_buf["Id"].IsNumber) { throw new SerializationException(); }  Id = _buf["Id"]; }
        { if(!_buf["Type"].IsNumber) { throw new SerializationException(); }  Type = _buf["Type"]; }
        { if(!_buf["Ranking"].IsNumber) { throw new SerializationException(); }  Ranking = _buf["Ranking"]; }
        { var __json0 = _buf["Reward"]; if(!__json0.IsArray) { throw new SerializationException(); } Reward = new System.Collections.Generic.List<ItemExchange>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { ItemExchange __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = ItemExchange.DeserializeItemExchange(__e0);  }  Reward.Add(__v0); }   }
        { if(!_buf["Txt"].IsString) { throw new SerializationException(); }  Txt = _buf["Txt"]; }
        { if(!_buf["RewardStr"].IsString) { throw new SerializationException(); }  RewardStr = _buf["RewardStr"]; }
    }

    public static Leaderboard DeserializeLeaderboard(JSONNode _buf)
    {
        return new Leaderboard(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 榜单类型
    /// </summary>
    public readonly int Type;
    /// <summary>
    /// 排名
    /// </summary>
    public readonly int Ranking;
    /// <summary>
    /// 排行奖励
    /// </summary>
    public readonly System.Collections.Generic.List<ItemExchange> Reward;
    /// <summary>
    /// 邮件文本
    /// </summary>
    public readonly string Txt;
    /// <summary>
    /// 奖励文本
    /// </summary>
    public readonly string RewardStr;
   
    public const int __ID__ = -38203555;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        foreach (var _e in Reward) { _e?.ResolveRef(tables); }
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Type:" + Type + ","
        + "Ranking:" + Ranking + ","
        + "Reward:" + Luban.StringUtil.CollectionToString(Reward) + ","
        + "Txt:" + Txt + ","
        + "RewardStr:" + RewardStr + ","
        + "}";
    }
}

}
