
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class LeaderboardConfig
{
    private readonly System.Collections.Generic.Dictionary<int, Leaderboard> _dataMap;
    private readonly System.Collections.Generic.List<Leaderboard> _dataList;
    
    public LeaderboardConfig(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Leaderboard>();
        _dataList = new System.Collections.Generic.List<Leaderboard>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            Leaderboard _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = Leaderboard.DeserializeLeaderboard(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Leaderboard> DataMap => _dataMap;
    public System.Collections.Generic.List<Leaderboard> DataList => _dataList;

    public Leaderboard GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Leaderboard Get(int key) => _dataMap[key];
    public Leaderboard this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

