
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class LevelModeConfig
{
    private readonly System.Collections.Generic.Dictionary<int, LevelMode> _dataMap;
    private readonly System.Collections.Generic.List<LevelMode> _dataList;
    
    public LevelModeConfig(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, LevelMode>();
        _dataList = new System.Collections.Generic.List<LevelMode>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            LevelMode _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = LevelMode.DeserializeLevelMode(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, LevelMode> DataMap => _dataMap;
    public System.Collections.Generic.List<LevelMode> DataList => _dataList;

    public LevelMode GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public LevelMode Get(int key) => _dataMap[key];
    public LevelMode this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

