
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class LevelMode : Luban.BeanBase
{
    public LevelMode(JSONNode _buf) 
    {
        { if(!_buf["Id"].IsNumber) { throw new SerializationException(); }  Id = _buf["Id"]; }
        { if(!_buf["Number"].IsNumber) { throw new SerializationException(); }  Number = _buf["Number"]; }
        { if(!_buf["Tickets"].IsNumber) { throw new SerializationException(); }  Tickets = _buf["Tickets"]; }
        { if(!_buf["Att"].IsNumber) { throw new SerializationException(); }  Att = _buf["Att"]; }
        { if(!_buf["Formations"].IsNumber) { throw new SerializationException(); }  Formations = _buf["Formations"]; }
        { if(!_buf["Session"].IsNumber) { throw new SerializationException(); }  Session = _buf["Session"]; }
        { var __json0 = _buf["FirstReward"]; if(!__json0.IsArray) { throw new SerializationException(); } FirstReward = new System.Collections.Generic.List<ItemExchange>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { ItemExchange __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = ItemExchange.DeserializeItemExchange(__e0);  }  FirstReward.Add(__v0); }   }
        { if(!_buf["BossId"].IsNumber) { throw new SerializationException(); }  BossId = _buf["BossId"]; }
        { if(!_buf["BossHp"].IsNumber) { throw new SerializationException(); }  BossHp = _buf["BossHp"]; }
        { if(!_buf["AiHp"].IsNumber) { throw new SerializationException(); }  AiHp = _buf["AiHp"]; }
    }

    public static LevelMode DeserializeLevelMode(JSONNode _buf)
    {
        return new LevelMode(_buf);
    }

    /// <summary>
    /// 关卡id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 关卡序号
    /// </summary>
    public readonly int Number;
    /// <summary>
    /// 入场条件
    /// </summary>
    public readonly int Tickets;
    /// <summary>
    /// 玩家炮口
    /// </summary>
    public readonly int Att;
    /// <summary>
    /// 阵法id
    /// </summary>
    public readonly int Formations;
    /// <summary>
    /// 场次
    /// </summary>
    public readonly int Session;
    /// <summary>
    /// 首通奖励
    /// </summary>
    public readonly System.Collections.Generic.List<ItemExchange> FirstReward;
    /// <summary>
    /// 首领id
    /// </summary>
    public readonly int BossId;
    /// <summary>
    /// 首领血量
    /// </summary>
    public readonly int BossHp;
    /// <summary>
    /// 怪物血量增长系数%
    /// </summary>
    public readonly int AiHp;
   
    public const int __ID__ = 347539239;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
        
        
        foreach (var _e in FirstReward) { _e?.ResolveRef(tables); }
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Number:" + Number + ","
        + "Tickets:" + Tickets + ","
        + "Att:" + Att + ","
        + "Formations:" + Formations + ","
        + "Session:" + Session + ","
        + "FirstReward:" + Luban.StringUtil.CollectionToString(FirstReward) + ","
        + "BossId:" + BossId + ","
        + "BossHp:" + BossHp + ","
        + "AiHp:" + AiHp + ","
        + "}";
    }
}

}
