
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class LevelConfig
{
    private readonly System.Collections.Generic.Dictionary<int, Level> _dataMap;
    private readonly System.Collections.Generic.List<Level> _dataList;
    
    public LevelConfig(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Level>();
        _dataList = new System.Collections.Generic.List<Level>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            Level _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = Level.DeserializeLevel(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Level> DataMap => _dataMap;
    public System.Collections.Generic.List<Level> DataList => _dataList;

    public Level GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Level Get(int key) => _dataMap[key];
    public Level this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

