
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class Level : Luban.BeanBase
{
    public Level(JSONNode _buf) 
    {
        { if(!_buf["Id"].IsNumber) { throw new SerializationException(); }  Id = _buf["Id"]; }
        { if(!_buf["Name"].IsString) { throw new SerializationException(); }  Name = _buf["Name"]; }
        { if(!_buf["Gold"].IsNumber) { throw new SerializationException(); }  Gold = _buf["Gold"]; }
        { var __json0 = _buf["Reward"]; if(!__json0.IsArray) { throw new SerializationException(); } Reward = new System.Collections.Generic.List<ItemExchange>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { ItemExchange __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = ItemExchange.DeserializeItemExchange(__e0);  }  Reward.Add(__v0); }   }
    }

    public static Level DeserializeLevel(JSONNode _buf)
    {
        return new Level(_buf);
    }

    /// <summary>
    /// 关卡id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 关卡名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 金币掉落
    /// </summary>
    public readonly int Gold;
    /// <summary>
    /// 首通奖励
    /// </summary>
    public readonly System.Collections.Generic.List<ItemExchange> Reward;
   
    public const int __ID__ = 73313124;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        foreach (var _e in Reward) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Name:" + Name + ","
        + "Gold:" + Gold + ","
        + "Reward:" + Luban.StringUtil.CollectionToString(Reward) + ","
        + "}";
    }
}

}
