
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class LevelMissionsConfig
{
    private readonly System.Collections.Generic.Dictionary<int, LevelMissions> _dataMap;
    private readonly System.Collections.Generic.List<LevelMissions> _dataList;
    
    public LevelMissionsConfig(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, LevelMissions>();
        _dataList = new System.Collections.Generic.List<LevelMissions>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            LevelMissions _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = LevelMissions.DeserializeLevelMissions(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, LevelMissions> DataMap => _dataMap;
    public System.Collections.Generic.List<LevelMissions> DataList => _dataList;

    public LevelMissions GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public LevelMissions Get(int key) => _dataMap[key];
    public LevelMissions this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

