
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class LuckyDrawing : Luban.BeanBase
{
    public LuckyDrawing(JSONNode _buf) 
    {
        { if(!_buf["Id"].IsNumber) { throw new SerializationException(); }  Id = _buf["Id"]; }
        { if(!_buf["Type"].IsNumber) { throw new SerializationException(); }  Type = _buf["Type"]; }
        { if(!_buf["Name"].IsString) { throw new SerializationException(); }  Name = _buf["Name"]; }
        { var __json0 = _buf["Rewards"]; if(!__json0.IsArray) { throw new SerializationException(); } Rewards = new System.Collections.Generic.List<ItemExchange>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { ItemExchange __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = ItemExchange.DeserializeItemExchange(__e0);  }  Rewards.Add(__v0); }   }
        { if(!_buf["Price"].IsNumber) { throw new SerializationException(); }  Price = _buf["Price"]; }
        { if(!_buf["Number"].IsNumber) { throw new SerializationException(); }  Number = _buf["Number"]; }
        { if(!_buf["Proportion"].IsNumber) { throw new SerializationException(); }  Proportion = _buf["Proportion"]; }
        { if(!_buf["Give"].IsNumber) { throw new SerializationException(); }  Give = _buf["Give"]; }
    }

    public static LuckyDrawing DeserializeLuckyDrawing(JSONNode _buf)
    {
        return new LuckyDrawing(_buf);
    }

    /// <summary>
    /// 礼包id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 幸运签类型
    /// </summary>
    public readonly int Type;
    /// <summary>
    /// 礼包名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 奖励魔币
    /// </summary>
    public readonly System.Collections.Generic.List<ItemExchange> Rewards;
    /// <summary>
    /// 支付价格
    /// </summary>
    public readonly int Price;
    /// <summary>
    /// 奖池增加数量
    /// </summary>
    public readonly int Number;
    /// <summary>
    /// (所有人)中奖瓜分百分比/100
    /// </summary>
    public readonly int Proportion;
    /// <summary>
    /// 参与奖强化石数量
    /// </summary>
    public readonly int Give;
   
    public const int __ID__ = -1259278282;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        foreach (var _e in Rewards) { _e?.ResolveRef(tables); }
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Type:" + Type + ","
        + "Name:" + Name + ","
        + "Rewards:" + Luban.StringUtil.CollectionToString(Rewards) + ","
        + "Price:" + Price + ","
        + "Number:" + Number + ","
        + "Proportion:" + Proportion + ","
        + "Give:" + Give + ","
        + "}";
    }
}

}
