
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class LuckyDrawingConfig
{
    private readonly System.Collections.Generic.Dictionary<int, LuckyDrawing> _dataMap;
    private readonly System.Collections.Generic.List<LuckyDrawing> _dataList;
    
    public LuckyDrawingConfig(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, LuckyDrawing>();
        _dataList = new System.Collections.Generic.List<LuckyDrawing>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            LuckyDrawing _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = LuckyDrawing.DeserializeLuckyDrawing(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, LuckyDrawing> DataMap => _dataMap;
    public System.Collections.Generic.List<LuckyDrawing> DataList => _dataList;

    public LuckyDrawing GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public LuckyDrawing Get(int key) => _dataMap[key];
    public LuckyDrawing this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

