
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class MagicCircle : Luban.BeanBase
{
    public MagicCircle(JSONNode _buf) 
    {
        { if(!_buf["Id"].IsNumber) { throw new SerializationException(); }  Id = _buf["Id"]; }
        { if(!_buf["Name"].IsString) { throw new SerializationException(); }  Name = _buf["Name"]; }
        { if(!_buf["Description"].IsString) { throw new SerializationException(); }  Description = _buf["Description"]; }
        { if(!_buf["Proportion"].IsNumber) { throw new SerializationException(); }  Proportion = _buf["Proportion"]; }
        { if(!_buf["Att"].IsNumber) { throw new SerializationException(); }  Att = _buf["Att"]; }
        { if(!_buf["AttributeBonus"].IsNumber) { throw new SerializationException(); }  AttributeBonus = _buf["AttributeBonus"]; }
        { if(!_buf["FormationLevel"].IsNumber) { throw new SerializationException(); }  FormationLevel = _buf["FormationLevel"]; }
        { if(!_buf["MissionSDescription"].IsString) { throw new SerializationException(); }  MissionSDescription = _buf["MissionSDescription"]; }
        { if(!_buf["Progress"].IsNumber) { throw new SerializationException(); }  Progress = _buf["Progress"]; }
    }

    public static MagicCircle DeserializeMagicCircle(JSONNode _buf)
    {
        return new MagicCircle(_buf);
    }

    /// <summary>
    /// 阵法id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 阵法名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 阵法描述
    /// </summary>
    public readonly string Description;
    /// <summary>
    /// 瓜分比例/1000
    /// </summary>
    public readonly int Proportion;
    /// <summary>
    /// 阵法所需魔币数量
    /// </summary>
    public readonly int Att;
    /// <summary>
    /// 阵法属性加成（攻击和生命固定值）
    /// </summary>
    public readonly int AttributeBonus;
    /// <summary>
    /// 阵法等级
    /// </summary>
    public readonly int FormationLevel;
    /// <summary>
    /// 解锁任务描述
    /// </summary>
    public readonly string MissionSDescription;
    /// <summary>
    /// 所需进度数量（魔能结晶数量)
    /// </summary>
    public readonly int Progress;
   
    public const int __ID__ = -1998830403;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
        
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Name:" + Name + ","
        + "Description:" + Description + ","
        + "Proportion:" + Proportion + ","
        + "Att:" + Att + ","
        + "AttributeBonus:" + AttributeBonus + ","
        + "FormationLevel:" + FormationLevel + ","
        + "MissionSDescription:" + MissionSDescription + ","
        + "Progress:" + Progress + ","
        + "}";
    }
}

}
