
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class MagicCircleConfig
{
    private readonly System.Collections.Generic.Dictionary<int, MagicCircle> _dataMap;
    private readonly System.Collections.Generic.List<MagicCircle> _dataList;
    
    public MagicCircleConfig(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, MagicCircle>();
        _dataList = new System.Collections.Generic.List<MagicCircle>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            MagicCircle _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = MagicCircle.DeserializeMagicCircle(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, MagicCircle> DataMap => _dataMap;
    public System.Collections.Generic.List<MagicCircle> DataList => _dataList;

    public MagicCircle GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public MagicCircle Get(int key) => _dataMap[key];
    public MagicCircle this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

