
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class MateridlConfig
{
    private readonly System.Collections.Generic.Dictionary<int, Materidl> _dataMap;
    private readonly System.Collections.Generic.List<Materidl> _dataList;
    
    public MateridlConfig(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Materidl>();
        _dataList = new System.Collections.Generic.List<Materidl>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            Materidl _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = Materidl.DeserializeMateridl(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Materidl> DataMap => _dataMap;
    public System.Collections.Generic.List<Materidl> DataList => _dataList;

    public Materidl GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Materidl Get(int key) => _dataMap[key];
    public Materidl this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

