
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class Matrix : Luban.BeanBase
{
    public Matrix(JSONNode _buf) 
    {
        { if(!_buf["Id"].IsNumber) { throw new SerializationException(); }  Id = _buf["Id"]; }
        { if(!_buf["StartStatus"].IsNumber) { throw new SerializationException(); }  StartStatus = _buf["StartStatus"]; }
        { if(!_buf["EndStatus"].IsNumber) { throw new SerializationException(); }  EndStatus = _buf["EndStatus"]; }
        { if(!_buf["WinType"].IsNumber) { throw new SerializationException(); }  WinType = _buf["WinType"]; }
        { if(!_buf["Weight"].IsNumber) { throw new SerializationException(); }  Weight = _buf["Weight"]; }
    }

    public static Matrix DeserializeMatrix(JSONNode _buf)
    {
        return new Matrix(_buf);
    }

    /// <summary>
    /// 状态ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 初始状态ID
    /// </summary>
    public readonly int StartStatus;
    /// <summary>
    /// 终止状态ID
    /// </summary>
    public readonly int EndStatus;
    /// <summary>
    /// 状态ID
    /// </summary>
    public readonly int WinType;
    /// <summary>
    /// 权重
    /// </summary>
    public readonly int Weight;
   
    public const int __ID__ = -1997372447;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "StartStatus:" + StartStatus + ","
        + "EndStatus:" + EndStatus + ","
        + "WinType:" + WinType + ","
        + "Weight:" + Weight + ","
        + "}";
    }
}

}
