
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class MatrixConfig
{
    private readonly System.Collections.Generic.Dictionary<int, Matrix> _dataMap;
    private readonly System.Collections.Generic.List<Matrix> _dataList;
    
    public MatrixConfig(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Matrix>();
        _dataList = new System.Collections.Generic.List<Matrix>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            Matrix _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = Matrix.DeserializeMatrix(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Matrix> DataMap => _dataMap;
    public System.Collections.Generic.List<Matrix> DataList => _dataList;

    public Matrix GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Matrix Get(int key) => _dataMap[key];
    public Matrix this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

