
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class MhGift : Luban.BeanBase
{
    public MhGift(JSONNode _buf) 
    {
        { if(!_buf["Id"].IsNumber) { throw new SerializationException(); }  Id = _buf["Id"]; }
        { if(!_buf["Name"].IsString) { throw new SerializationException(); }  Name = _buf["Name"]; }
        { if(!_buf["MagicCoins"].IsNumber) { throw new SerializationException(); }  MagicCoins = _buf["MagicCoins"]; }
        { if(!_buf["MagicStone"].IsNumber) { throw new SerializationException(); }  MagicStone = _buf["MagicStone"]; }
        { if(!_buf["Price"].IsNumber) { throw new SerializationException(); }  Price = _buf["Price"]; }
    }

    public static MhGift DeserializeMhGift(JSONNode _buf)
    {
        return new MhGift(_buf);
    }

    /// <summary>
    /// 礼包id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 礼包名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 魔币奖励
    /// </summary>
    public readonly int MagicCoins;
    /// <summary>
    /// 盲盒次数
    /// </summary>
    public readonly int MagicStone;
    /// <summary>
    /// 礼包价格
    /// </summary>
    public readonly int Price;
   
    public const int __ID__ = -1992257141;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Name:" + Name + ","
        + "MagicCoins:" + MagicCoins + ","
        + "MagicStone:" + MagicStone + ","
        + "Price:" + Price + ","
        + "}";
    }
}

}
