
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class MhGiftConfig
{
    private readonly System.Collections.Generic.Dictionary<int, MhGift> _dataMap;
    private readonly System.Collections.Generic.List<MhGift> _dataList;
    
    public MhGiftConfig(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, MhGift>();
        _dataList = new System.Collections.Generic.List<MhGift>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            MhGift _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = MhGift.DeserializeMhGift(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, MhGift> DataMap => _dataMap;
    public System.Collections.Generic.List<MhGift> DataList => _dataList;

    public MhGift GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public MhGift Get(int key) => _dataMap[key];
    public MhGift this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

