
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class MhlistConfig
{
    private readonly System.Collections.Generic.Dictionary<int, Mhlist> _dataMap;
    private readonly System.Collections.Generic.List<Mhlist> _dataList;
    
    public MhlistConfig(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Mhlist>();
        _dataList = new System.Collections.Generic.List<Mhlist>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            Mhlist _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = Mhlist.DeserializeMhlist(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Mhlist> DataMap => _dataMap;
    public System.Collections.Generic.List<Mhlist> DataList => _dataList;

    public Mhlist GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Mhlist Get(int key) => _dataMap[key];
    public Mhlist this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

