
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class Mhlist : Luban.BeanBase
{
    public Mhlist(JSONNode _buf) 
    {
        { if(!_buf["Id"].IsNumber) { throw new SerializationException(); }  Id = _buf["Id"]; }
        { if(!_buf["TimesList"].IsNumber) { throw new SerializationException(); }  TimesList = _buf["TimesList"]; }
    }

    public static Mhlist DeserializeMhlist(JSONNode _buf)
    {
        return new Mhlist(_buf);
    }

    /// <summary>
    /// 名次id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 盲盒次数榜(魔币)
    /// </summary>
    public readonly int TimesList;
   
    public const int __ID__ = -1991154471;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "TimesList:" + TimesList + ","
        + "}";
    }
}

}
