
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class MhPrizeConfig
{
    private readonly System.Collections.Generic.Dictionary<int, MhPrize> _dataMap;
    private readonly System.Collections.Generic.List<MhPrize> _dataList;
    
    public MhPrizeConfig(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, MhPrize>();
        _dataList = new System.Collections.Generic.List<MhPrize>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            MhPrize _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = MhPrize.DeserializeMhPrize(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, MhPrize> DataMap => _dataMap;
    public System.Collections.Generic.List<MhPrize> DataList => _dataList;

    public MhPrize GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public MhPrize Get(int key) => _dataMap[key];
    public MhPrize this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

