
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class MhPrize : Luban.BeanBase
{
    public MhPrize(JSONNode _buf) 
    {
        { if(!_buf["Id"].IsNumber) { throw new SerializationException(); }  Id = _buf["Id"]; }
        { if(!_buf["Type"].IsNumber) { throw new SerializationException(); }  Type = _buf["Type"]; }
        { if(!_buf["Reward"].IsNumber) { throw new SerializationException(); }  Reward = _buf["Reward"]; }
        { if(!_buf["Number"].IsNumber) { throw new SerializationException(); }  Number = _buf["Number"]; }
        { if(!_buf["Probability"].IsNumber) { throw new SerializationException(); }  Probability = _buf["Probability"]; }
    }

    public static MhPrize DeserializeMhPrize(JSONNode _buf)
    {
        return new MhPrize(_buf);
    }

    /// <summary>
    /// 奖励id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 类型
    /// </summary>
    public readonly int Type;
    /// <summary>
    /// 奖励类型
    /// </summary>
    public readonly int Reward;
    /// <summary>
    /// 奖励数量
    /// </summary>
    public readonly int Number;
    /// <summary>
    /// 概率/1000
    /// </summary>
    public readonly int Probability;
   
    public const int __ID__ = -1621846249;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Type:" + Type + ","
        + "Reward:" + Reward + ","
        + "Number:" + Number + ","
        + "Probability:" + Probability + ","
        + "}";
    }
}

}
