
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class MonthlyPass : Luban.BeanBase
{
    public MonthlyPass(JSONNode _buf) 
    {
        { if(!_buf["Id"].IsNumber) { throw new SerializationException(); }  Id = _buf["Id"]; }
        { if(!_buf["Name"].IsString) { throw new SerializationException(); }  Name = _buf["Name"]; }
        { var __json0 = _buf["Reward"]; if(!__json0.IsArray) { throw new SerializationException(); } Reward = new System.Collections.Generic.List<ItemExchange>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { ItemExchange __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = ItemExchange.DeserializeItemExchange(__e0);  }  Reward.Add(__v0); }   }
        { var __json0 = _buf["Daily_rewards"]; if(!__json0.IsArray) { throw new SerializationException(); } DailyRewards = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  DailyRewards.Add(__v0); }   }
        { if(!_buf["Days"].IsNumber) { throw new SerializationException(); }  Days = _buf["Days"]; }
        { if(!_buf["Price"].IsNumber) { throw new SerializationException(); }  Price = _buf["Price"]; }
    }

    public static MonthlyPass DeserializeMonthlyPass(JSONNode _buf)
    {
        return new MonthlyPass(_buf);
    }

    /// <summary>
    /// 月卡id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 月卡名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 购买奖励
    /// </summary>
    public readonly System.Collections.Generic.List<ItemExchange> Reward;
    /// <summary>
    /// 每日奖励
    /// </summary>
    public readonly System.Collections.Generic.List<int> DailyRewards;
    /// <summary>
    /// 特权时长/天
    /// </summary>
    public readonly int Days;
    /// <summary>
    /// 月卡价格
    /// </summary>
    public readonly int Price;
   
    public const int __ID__ = -1196146274;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        foreach (var _e in Reward) { _e?.ResolveRef(tables); }
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Name:" + Name + ","
        + "Reward:" + Luban.StringUtil.CollectionToString(Reward) + ","
        + "DailyRewards:" + Luban.StringUtil.CollectionToString(DailyRewards) + ","
        + "Days:" + Days + ","
        + "Price:" + Price + ","
        + "}";
    }
}

}
