
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class MonthlyPassConfig
{
    private readonly System.Collections.Generic.Dictionary<int, MonthlyPass> _dataMap;
    private readonly System.Collections.Generic.List<MonthlyPass> _dataList;
    
    public MonthlyPassConfig(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, MonthlyPass>();
        _dataList = new System.Collections.Generic.List<MonthlyPass>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            MonthlyPass _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = MonthlyPass.DeserializeMonthlyPass(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, MonthlyPass> DataMap => _dataMap;
    public System.Collections.Generic.List<MonthlyPass> DataList => _dataList;

    public MonthlyPass GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public MonthlyPass Get(int key) => _dataMap[key];
    public MonthlyPass this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

