
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class PerDayGiftPack : Luban.BeanBase
{
    public PerDayGiftPack(JSONNode _buf) 
    {
        { if(!_buf["Id"].IsNumber) { throw new SerializationException(); }  Id = _buf["Id"]; }
        { if(!_buf["Price"].IsNumber) { throw new SerializationException(); }  Price = _buf["Price"]; }
        { if(!_buf["OriginalPrice"].IsNumber) { throw new SerializationException(); }  OriginalPrice = _buf["OriginalPrice"]; }
        { if(!_buf["Reward"].IsNumber) { throw new SerializationException(); }  Reward = _buf["Reward"]; }
        { if(!_buf["OriginalNum"].IsNumber) { throw new SerializationException(); }  OriginalNum = _buf["OriginalNum"]; }
        { if(!_buf["GiveNum"].IsNumber) { throw new SerializationException(); }  GiveNum = _buf["GiveNum"]; }
    }

    public static PerDayGiftPack DeserializePerDayGiftPack(JSONNode _buf)
    {
        return new PerDayGiftPack(_buf);
    }

    /// <summary>
    /// 这是id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 实际价格
    /// </summary>
    public readonly int Price;
    /// <summary>
    /// 原价（展示用）
    /// </summary>
    public readonly int OriginalPrice;
    /// <summary>
    /// 奖励物品Id
    /// </summary>
    public readonly int Reward;
    /// <summary>
    /// 奖励物品原数量
    /// </summary>
    public readonly int OriginalNum;
    /// <summary>
    /// 额外赠送奖励物品数量
    /// </summary>
    public readonly int GiveNum;
   
    public const int __ID__ = -2088726040;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Price:" + Price + ","
        + "OriginalPrice:" + OriginalPrice + ","
        + "Reward:" + Reward + ","
        + "OriginalNum:" + OriginalNum + ","
        + "GiveNum:" + GiveNum + ","
        + "}";
    }
}

}
