
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class PerDayGiftPackConfig
{
    private readonly System.Collections.Generic.Dictionary<int, PerDayGiftPack> _dataMap;
    private readonly System.Collections.Generic.List<PerDayGiftPack> _dataList;
    
    public PerDayGiftPackConfig(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, PerDayGiftPack>();
        _dataList = new System.Collections.Generic.List<PerDayGiftPack>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            PerDayGiftPack _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = PerDayGiftPack.DeserializePerDayGiftPack(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, PerDayGiftPack> DataMap => _dataMap;
    public System.Collections.Generic.List<PerDayGiftPack> DataList => _dataList;

    public PerDayGiftPack GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public PerDayGiftPack Get(int key) => _dataMap[key];
    public PerDayGiftPack this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

