
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class PiggyBank : Luban.BeanBase
{
    public PiggyBank(JSONNode _buf) 
    {
        { if(!_buf["Id"].IsNumber) { throw new SerializationException(); }  Id = _buf["Id"]; }
        { if(!_buf["Vip"].IsNumber) { throw new SerializationException(); }  Vip = _buf["Vip"]; }
        { if(!_buf["Number"].IsNumber) { throw new SerializationException(); }  Number = _buf["Number"]; }
        { if(!_buf["Give"].IsNumber) { throw new SerializationException(); }  Give = _buf["Give"]; }
        { if(!_buf["Price"].IsNumber) { throw new SerializationException(); }  Price = _buf["Price"]; }
    }

    public static PiggyBank DeserializePiggyBank(JSONNode _buf)
    {
        return new PiggyBank(_buf);
    }

    /// <summary>
    /// 存钱罐id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// vip等级
    /// </summary>
    public readonly int Vip;
    /// <summary>
    /// 数量上限
    /// </summary>
    public readonly int Number;
    /// <summary>
    /// 赠送魔币数量
    /// </summary>
    public readonly int Give;
    /// <summary>
    /// 打开价格
    /// </summary>
    public readonly int Price;
   
    public const int __ID__ = -269767364;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Vip:" + Vip + ","
        + "Number:" + Number + ","
        + "Give:" + Give + ","
        + "Price:" + Price + ","
        + "}";
    }
}

}
