
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class PiggyBankConfig
{
    private readonly System.Collections.Generic.Dictionary<int, PiggyBank> _dataMap;
    private readonly System.Collections.Generic.List<PiggyBank> _dataList;
    
    public PiggyBankConfig(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, PiggyBank>();
        _dataList = new System.Collections.Generic.List<PiggyBank>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            PiggyBank _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = PiggyBank.DeserializePiggyBank(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, PiggyBank> DataMap => _dataMap;
    public System.Collections.Generic.List<PiggyBank> DataList => _dataList;

    public PiggyBank GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public PiggyBank Get(int key) => _dataMap[key];
    public PiggyBank this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

