
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class PlayerUpgrade : Luban.BeanBase
{
    public PlayerUpgrade(JSONNode _buf) 
    {
        { if(!_buf["Id"].IsNumber) { throw new SerializationException(); }  Id = _buf["Id"]; }
        { if(!_buf["Exp"].IsNumber) { throw new SerializationException(); }  Exp = _buf["Exp"]; }
    }

    public static PlayerUpgrade DeserializePlayerUpgrade(JSONNode _buf)
    {
        return new PlayerUpgrade(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 名字
    /// </summary>
    public readonly int Exp;
   
    public const int __ID__ = -1074202661;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Exp:" + Exp + ","
        + "}";
    }
}

}
