
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class PlayerUpgradeConfig
{
    private readonly System.Collections.Generic.Dictionary<int, PlayerUpgrade> _dataMap;
    private readonly System.Collections.Generic.List<PlayerUpgrade> _dataList;
    
    public PlayerUpgradeConfig(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, PlayerUpgrade>();
        _dataList = new System.Collections.Generic.List<PlayerUpgrade>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            PlayerUpgrade _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = PlayerUpgrade.DeserializePlayerUpgrade(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, PlayerUpgrade> DataMap => _dataMap;
    public System.Collections.Generic.List<PlayerUpgrade> DataList => _dataList;

    public PlayerUpgrade GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public PlayerUpgrade Get(int key) => _dataMap[key];
    public PlayerUpgrade this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

