
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class PushFunctionalitySetting : Luban.BeanBase
{
    public PushFunctionalitySetting(JSONNode _buf) 
    {
        { if(!_buf["Id"].IsNumber) { throw new SerializationException(); }  Id = _buf["Id"]; }
        { if(!_buf["FunactionalityName"].IsString) { throw new SerializationException(); }  FunactionalityName = _buf["FunactionalityName"]; }
        { if(!_buf["CurrentType"].IsString) { throw new SerializationException(); }  CurrentType = _buf["CurrentType"]; }
        { if(!_buf["TimeCondition"].IsNumber) { throw new SerializationException(); }  TimeCondition = _buf["TimeCondition"]; }
        { if(!_buf["MillisecondValue"].IsNumber) { throw new SerializationException(); }  MillisecondValue = _buf["MillisecondValue"]; }
        { if(!_buf["NextType"].IsNumber) { throw new SerializationException(); }  NextType = _buf["NextType"]; }
    }

    public static PushFunctionalitySetting DeserializePushFunctionalitySetting(JSONNode _buf)
    {
        return new PushFunctionalitySetting(_buf);
    }

    /// <summary>
    /// 枚举ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 功能中文名称
    /// </summary>
    public readonly string FunactionalityName;
    /// <summary>
    /// 功能类型名称-程序类名
    /// </summary>
    public readonly string CurrentType;
    /// <summary>
    /// 时间控制条件
    /// </summary>
    public readonly int TimeCondition;
    /// <summary>
    /// 时间-单位/毫秒
    /// </summary>
    public readonly int MillisecondValue;
    /// <summary>
    /// 当前界面关闭时-下个连续调起的功能
    /// </summary>
    public readonly int NextType;
   
    public const int __ID__ = -1101101473;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "FunactionalityName:" + FunactionalityName + ","
        + "CurrentType:" + CurrentType + ","
        + "TimeCondition:" + TimeCondition + ","
        + "MillisecondValue:" + MillisecondValue + ","
        + "NextType:" + NextType + ","
        + "}";
    }
}

}
