
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class PushFunctionalitySettingConfig
{
    private readonly System.Collections.Generic.Dictionary<int, PushFunctionalitySetting> _dataMap;
    private readonly System.Collections.Generic.List<PushFunctionalitySetting> _dataList;
    
    public PushFunctionalitySettingConfig(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, PushFunctionalitySetting>();
        _dataList = new System.Collections.Generic.List<PushFunctionalitySetting>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            PushFunctionalitySetting _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = PushFunctionalitySetting.DeserializePushFunctionalitySetting(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, PushFunctionalitySetting> DataMap => _dataMap;
    public System.Collections.Generic.List<PushFunctionalitySetting> DataList => _dataList;

    public PushFunctionalitySetting GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public PushFunctionalitySetting Get(int key) => _dataMap[key];
    public PushFunctionalitySetting this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

