
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class Random : Luban.BeanBase
{
    public Random(JSONNode _buf) 
    {
        { if(!_buf["Id"].IsNumber) { throw new SerializationException(); }  Id = _buf["Id"]; }
        { if(!_buf["Buff"].IsNumber) { throw new SerializationException(); }  Buff = _buf["Buff"]; }
        { if(!_buf["Probability"].IsNumber) { throw new SerializationException(); }  Probability = _buf["Probability"]; }
        { if(!_buf["Ground"].IsNumber) { throw new SerializationException(); }  Ground = _buf["Ground"]; }
        { var __json0 = _buf["FishPrice"]; if(!__json0.IsArray) { throw new SerializationException(); } FishPrice = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  FishPrice.Add(__v0); }   }
        { var __json0 = _buf["Bullet"]; if(!__json0.IsArray) { throw new SerializationException(); } Bullet = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  Bullet.Add(__v0); }   }
    }

    public static Random DeserializeRandom(JSONNode _buf)
    {
        return new Random(_buf);
    }

    /// <summary>
    /// 座位id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// buff/1000
    /// </summary>
    public readonly int Buff;
    /// <summary>
    /// 概率%/1000
    /// </summary>
    public readonly int Probability;
    /// <summary>
    /// 生效场次
    /// </summary>
    public readonly int Ground;
    /// <summary>
    /// 生效倍率区间
    /// </summary>
    public readonly System.Collections.Generic.List<int> FishPrice;
    /// <summary>
    /// 子弹区间
    /// </summary>
    public readonly System.Collections.Generic.List<int> Bullet;
   
    public const int __ID__ = -1854418717;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Buff:" + Buff + ","
        + "Probability:" + Probability + ","
        + "Ground:" + Ground + ","
        + "FishPrice:" + Luban.StringUtil.CollectionToString(FishPrice) + ","
        + "Bullet:" + Luban.StringUtil.CollectionToString(Bullet) + ","
        + "}";
    }
}

}
