
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class RandomConfig
{
    private readonly System.Collections.Generic.Dictionary<int, Random> _dataMap;
    private readonly System.Collections.Generic.List<Random> _dataList;
    
    public RandomConfig(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Random>();
        _dataList = new System.Collections.Generic.List<Random>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            Random _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = Random.DeserializeRandom(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Random> DataMap => _dataMap;
    public System.Collections.Generic.List<Random> DataList => _dataList;

    public Random GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Random Get(int key) => _dataMap[key];
    public Random this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

