
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class RechargeGoodsInfoConfig
{
    private readonly System.Collections.Generic.Dictionary<int, RechargeGoodsInfo> _dataMap;
    private readonly System.Collections.Generic.List<RechargeGoodsInfo> _dataList;
    
    public RechargeGoodsInfoConfig(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, RechargeGoodsInfo>();
        _dataList = new System.Collections.Generic.List<RechargeGoodsInfo>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            RechargeGoodsInfo _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = RechargeGoodsInfo.DeserializeRechargeGoodsInfo(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, RechargeGoodsInfo> DataMap => _dataMap;
    public System.Collections.Generic.List<RechargeGoodsInfo> DataList => _dataList;

    public RechargeGoodsInfo GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public RechargeGoodsInfo Get(int key) => _dataMap[key];
    public RechargeGoodsInfo this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

