
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class RechargeBuff : Luban.BeanBase
{
    public RechargeBuff(JSONNode _buf) 
    {
        { if(!_buf["Id"].IsNumber) { throw new SerializationException(); }  Id = _buf["Id"]; }
        { if(!_buf["Min"].IsNumber) { throw new SerializationException(); }  Min = _buf["Min"]; }
        { if(!_buf["Max"].IsNumber) { throw new SerializationException(); }  Max = _buf["Max"]; }
        { if(!_buf["Zdamount"].IsNumber) { throw new SerializationException(); }  Zdamount = _buf["Zdamount"]; }
        { if(!_buf["Recbuff"].IsNumber) { throw new SerializationException(); }  Recbuff = _buf["Recbuff"]; }
        { var __json0 = _buf["FishPrice"]; if(!__json0.IsArray) { throw new SerializationException(); } FishPrice = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  FishPrice.Add(__v0); }   }
        { if(!_buf["OnceBullet"].IsNumber) { throw new SerializationException(); }  OnceBullet = _buf["OnceBullet"]; }
        { if(!_buf["OncePrice"].IsNumber) { throw new SerializationException(); }  OncePrice = _buf["OncePrice"]; }
    }

    public static RechargeBuff DeserializeRechargeBuff(JSONNode _buf)
    {
        return new RechargeBuff(_buf);
    }

    /// <summary>
    /// 区间id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 单笔充值下限
    /// </summary>
    public readonly int Min;
    /// <summary>
    /// 单笔充值上限
    /// </summary>
    public readonly int Max;
    /// <summary>
    /// 子弹数量
    /// </summary>
    public readonly int Zdamount;
    /// <summary>
    /// buff值/1000
    /// </summary>
    public readonly int Recbuff;
    /// <summary>
    /// 生效倍率区间
    /// </summary>
    public readonly System.Collections.Generic.List<int> FishPrice;
    /// <summary>
    /// 必中子弹数
    /// </summary>
    public readonly int OnceBullet;
    /// <summary>
    /// 必中怪倍率
    /// </summary>
    public readonly int OncePrice;
   
    public const int __ID__ = -1986008134;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Min:" + Min + ","
        + "Max:" + Max + ","
        + "Zdamount:" + Zdamount + ","
        + "Recbuff:" + Recbuff + ","
        + "FishPrice:" + Luban.StringUtil.CollectionToString(FishPrice) + ","
        + "OnceBullet:" + OnceBullet + ","
        + "OncePrice:" + OncePrice + ","
        + "}";
    }
}

}
