
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class RechargeGoodsInfo : Luban.BeanBase
{
    public RechargeGoodsInfo(JSONNode _buf) 
    {
        { if(!_buf["Id"].IsNumber) { throw new SerializationException(); }  Id = _buf["Id"]; }
        { if(!_buf["Price"].IsNumber) { throw new SerializationException(); }  Price = _buf["Price"]; }
        { if(!_buf["Describe"].IsString) { throw new SerializationException(); }  Describe = _buf["Describe"]; }
        { if(!_buf["GoodsType"].IsNumber) { throw new SerializationException(); }  GoodsType = _buf["GoodsType"]; }
        { if(!_buf["SaveType"].IsNumber) { throw new SerializationException(); }  SaveType = _buf["SaveType"]; }
    }

    public static RechargeGoodsInfo DeserializeRechargeGoodsInfo(JSONNode _buf)
    {
        return new RechargeGoodsInfo(_buf);
    }

    /// <summary>
    /// 充值商品id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 商品价格元
    /// </summary>
    public readonly int Price;
    /// <summary>
    /// 商品说明
    /// </summary>
    public readonly string Describe;
    /// <summary>
    /// 商品类型
    /// </summary>
    public readonly int GoodsType;
    /// <summary>
    /// 保存类型
    /// </summary>
    public readonly int SaveType;
   
    public const int __ID__ = 926237213;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Price:" + Price + ","
        + "Describe:" + Describe + ","
        + "GoodsType:" + GoodsType + ","
        + "SaveType:" + SaveType + ","
        + "}";
    }
}

}
