
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class RechargeLimit : Luban.BeanBase
{
    public RechargeLimit(JSONNode _buf) 
    {
        { if(!_buf["Id"].IsNumber) { throw new SerializationException(); }  Id = _buf["Id"]; }
        { if(!_buf["MinRecharge"].IsNumber) { throw new SerializationException(); }  MinRecharge = _buf["MinRecharge"]; }
        { if(!_buf["MaxRecharge"].IsNumber) { throw new SerializationException(); }  MaxRecharge = _buf["MaxRecharge"]; }
        { if(!_buf["IsNew"].IsNumber) { throw new SerializationException(); }  IsNew = _buf["IsNew"]; }
        { var __json0 = _buf["DownLimitPerc"]; if(!__json0.IsArray) { throw new SerializationException(); } DownLimitPerc = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  DownLimitPerc.Add(__v0); }   }
        { var __json0 = _buf["DownLimitBuff"]; if(!__json0.IsArray) { throw new SerializationException(); } DownLimitBuff = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  DownLimitBuff.Add(__v0); }   }
        { var __json0 = _buf["UpLimitPerc"]; if(!__json0.IsArray) { throw new SerializationException(); } UpLimitPerc = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  UpLimitPerc.Add(__v0); }   }
        { var __json0 = _buf["UpLimitBuff"]; if(!__json0.IsArray) { throw new SerializationException(); } UpLimitBuff = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  UpLimitBuff.Add(__v0); }   }
    }

    public static RechargeLimit DeserializeRechargeLimit(JSONNode _buf)
    {
        return new RechargeLimit(_buf);
    }

    /// <summary>
    /// 状态流水号
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 充值额下限
    /// </summary>
    public readonly int MinRecharge;
    /// <summary>
    /// 充值额上限
    /// </summary>
    public readonly int MaxRecharge;
    /// <summary>
    /// 是否新手（0只有减益，1有减有增）
    /// </summary>
    public readonly int IsNew;
    /// <summary>
    /// 减益限制百分比
    /// </summary>
    public readonly System.Collections.Generic.List<int> DownLimitPerc;
    /// <summary>
    /// 减益Buff（百分比）
    /// </summary>
    public readonly System.Collections.Generic.List<int> DownLimitBuff;
    /// <summary>
    /// 增益限制百分比
    /// </summary>
    public readonly System.Collections.Generic.List<int> UpLimitPerc;
    /// <summary>
    /// 增益Buff（百分比）
    /// </summary>
    public readonly System.Collections.Generic.List<int> UpLimitBuff;
   
    public const int __ID__ = -1427825356;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "MinRecharge:" + MinRecharge + ","
        + "MaxRecharge:" + MaxRecharge + ","
        + "IsNew:" + IsNew + ","
        + "DownLimitPerc:" + Luban.StringUtil.CollectionToString(DownLimitPerc) + ","
        + "DownLimitBuff:" + Luban.StringUtil.CollectionToString(DownLimitBuff) + ","
        + "UpLimitPerc:" + Luban.StringUtil.CollectionToString(UpLimitPerc) + ","
        + "UpLimitBuff:" + Luban.StringUtil.CollectionToString(UpLimitBuff) + ","
        + "}";
    }
}

}
