
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class Session3 : Luban.BeanBase
{
    public Session3(JSONNode _buf) 
    {
        { if(!_buf["Id"].IsNumber) { throw new SerializationException(); }  Id = _buf["Id"]; }
        { if(!_buf["TargetPlay"].IsNumber) { throw new SerializationException(); }  TargetPlay = _buf["TargetPlay"]; }
        { if(!_buf["MinCurrencyValue"].IsNumber) { throw new SerializationException(); }  MinCurrencyValue = _buf["MinCurrencyValue"]; }
        { if(!_buf["MaxCurrencyValue"].IsNumber) { throw new SerializationException(); }  MaxCurrencyValue = _buf["MaxCurrencyValue"]; }
        { if(!_buf["ChanceAdjust"].IsNumber) { throw new SerializationException(); }  ChanceAdjust = _buf["ChanceAdjust"]; }
    }

    public static Session3 DeserializeSession3(JSONNode _buf)
    {
        return new Session3(_buf);
    }

    /// <summary>
    /// 规则id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 场次id
    /// </summary>
    public readonly int TargetPlay;
    /// <summary>
    /// 下限
    /// </summary>
    public readonly long MinCurrencyValue;
    /// <summary>
    /// 上限
    /// </summary>
    public readonly long MaxCurrencyValue;
    /// <summary>
    /// 概率/100
    /// </summary>
    public readonly int ChanceAdjust;
   
    public const int __ID__ = 1469723773;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "TargetPlay:" + TargetPlay + ","
        + "MinCurrencyValue:" + MinCurrencyValue + ","
        + "MaxCurrencyValue:" + MaxCurrencyValue + ","
        + "ChanceAdjust:" + ChanceAdjust + ","
        + "}";
    }
}

}
