
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class Session : Luban.BeanBase
{
    public Session(JSONNode _buf) 
    {
        { if(!_buf["Id"].IsNumber) { throw new SerializationException(); }  Id = _buf["Id"]; }
        { if(!_buf["Type"].IsNumber) { throw new SerializationException(); }  Type = _buf["Type"]; }
        { if(!_buf["Name"].IsString) { throw new SerializationException(); }  Name = _buf["Name"]; }
        { var __json0 = _buf["MagicCircle"]; if(!__json0.IsArray) { throw new SerializationException(); } MagicCircle = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  MagicCircle.Add(__v0); }   }
        { if(!_buf["MagicCoins"].IsNumber) { throw new SerializationException(); }  MagicCoins = _buf["MagicCoins"]; }
        { if(!_buf["Inventory"].IsNumber) { throw new SerializationException(); }  Inventory = _buf["Inventory"]; }
        { if(!_buf["Condition"].IsNumber) { throw new SerializationException(); }  Condition = _buf["Condition"]; }
        { if(!_buf["Tax1"].IsNumber) { throw new SerializationException(); }  Tax1 = _buf["Tax1"]; }
        { if(!_buf["Tax2"].IsNumber) { throw new SerializationException(); }  Tax2 = _buf["Tax2"]; }
        { if(!_buf["Float"].IsNumber) { throw new SerializationException(); }  Float = _buf["Float"]; }
        { if(!_buf["Extramax"].IsNumber) { throw new SerializationException(); }  Extramax = _buf["Extramax"]; }
        { if(!_buf["Extramin"].IsNumber) { throw new SerializationException(); }  Extramin = _buf["Extramin"]; }
        { if(!_buf["Coefficientmax"].IsNumber) { throw new SerializationException(); }  Coefficientmax = _buf["Coefficientmax"]; }
        { if(!_buf["Coefficientmin"].IsNumber) { throw new SerializationException(); }  Coefficientmin = _buf["Coefficientmin"]; }
        { if(!_buf["Condition1"].IsNumber) { throw new SerializationException(); }  Condition1 = _buf["Condition1"]; }
        { if(!_buf["Condition2"].IsNumber) { throw new SerializationException(); }  Condition2 = _buf["Condition2"]; }
        { var __json0 = _buf["BossTime"]; if(!__json0.IsArray) { throw new SerializationException(); } BossTime = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  BossTime.Add(__v0); }   }
        { if(!_buf["Condition3"].IsNumber) { throw new SerializationException(); }  Condition3 = _buf["Condition3"]; }
        { if(!_buf["Condition4"].IsNumber) { throw new SerializationException(); }  Condition4 = _buf["Condition4"]; }
    }

    public static Session DeserializeSession(JSONNode _buf)
    {
        return new Session(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 类型/场次
    /// </summary>
    public readonly int Type;
    /// <summary>
    /// 地图名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 阵法id
    /// </summary>
    public readonly System.Collections.Generic.List<int> MagicCircle;
    /// <summary>
    /// 魔能结晶掉落所需消耗魔币数量
    /// </summary>
    public readonly int MagicCoins;
    /// <summary>
    /// 真实库存线
    /// </summary>
    public readonly long Inventory;
    /// <summary>
    /// 判定条件（库存数量浮动）/1000
    /// </summary>
    public readonly int Condition;
    /// <summary>
    /// 金币税收/1000
    /// </summary>
    public readonly int Tax1;
    /// <summary>
    /// mon税收/1000
    /// </summary>
    public readonly int Tax2;
    /// <summary>
    /// 变化值（库存概率）/1000
    /// </summary>
    public readonly int Float;
    /// <summary>
    /// 最大库存概率/1000
    /// </summary>
    public readonly int Extramax;
    /// <summary>
    /// 最小库存概率/1000
    /// </summary>
    public readonly int Extramin;
    /// <summary>
    /// 最大掉落系数/1000
    /// </summary>
    public readonly int Coefficientmax;
    /// <summary>
    /// 最小掉落系数/1000
    /// </summary>
    public readonly int Coefficientmin;
    /// <summary>
    /// 入场条件1(阵法解锁等级)
    /// </summary>
    public readonly int Condition1;
    /// <summary>
    /// 入场条件2（魔币）
    /// </summary>
    public readonly long Condition2;
    /// <summary>
    /// boss刷新时间秒
    /// </summary>
    public readonly System.Collections.Generic.List<int> BossTime;
    /// <summary>
    /// 限制进入条件（魔法阵等级达到x）
    /// </summary>
    public readonly int Condition3;
    /// <summary>
    /// 限制进入条件（魔币数量大于x）
    /// </summary>
    public readonly int Condition4;
   
    public const int __ID__ = -645326218;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Type:" + Type + ","
        + "Name:" + Name + ","
        + "MagicCircle:" + Luban.StringUtil.CollectionToString(MagicCircle) + ","
        + "MagicCoins:" + MagicCoins + ","
        + "Inventory:" + Inventory + ","
        + "Condition:" + Condition + ","
        + "Tax1:" + Tax1 + ","
        + "Tax2:" + Tax2 + ","
        + "Float:" + Float + ","
        + "Extramax:" + Extramax + ","
        + "Extramin:" + Extramin + ","
        + "Coefficientmax:" + Coefficientmax + ","
        + "Coefficientmin:" + Coefficientmin + ","
        + "Condition1:" + Condition1 + ","
        + "Condition2:" + Condition2 + ","
        + "BossTime:" + Luban.StringUtil.CollectionToString(BossTime) + ","
        + "Condition3:" + Condition3 + ","
        + "Condition4:" + Condition4 + ","
        + "}";
    }
}

}
