
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class Session2Config
{
    private readonly System.Collections.Generic.Dictionary<int, Session3> _dataMap;
    private readonly System.Collections.Generic.List<Session3> _dataList;
    
    public Session2Config(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Session3>();
        _dataList = new System.Collections.Generic.List<Session3>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            Session3 _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = Session3.DeserializeSession3(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Session3> DataMap => _dataMap;
    public System.Collections.Generic.List<Session3> DataList => _dataList;

    public Session3 GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Session3 Get(int key) => _dataMap[key];
    public Session3 this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

