
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class Shop : Luban.BeanBase
{
    public Shop(JSONNode _buf) 
    {
        { if(!_buf["Id"].IsNumber) { throw new SerializationException(); }  Id = _buf["Id"]; }
        { if(!_buf["Type"].IsNumber) { throw new SerializationException(); }  Type = _buf["Type"]; }
        { if(!_buf["Items"].IsNumber) { throw new SerializationException(); }  Items = _buf["Items"]; }
        { if(!_buf["Quantity"].IsNumber) { throw new SerializationException(); }  Quantity = _buf["Quantity"]; }
        { if(!_buf["Payamount"].IsNumber) { throw new SerializationException(); }  Payamount = _buf["Payamount"]; }
        { if(!_buf["Discount"].IsNumber) { throw new SerializationException(); }  Discount = _buf["Discount"]; }
        { if(!_buf["Paytimes"].IsNumber) { throw new SerializationException(); }  Paytimes = _buf["Paytimes"]; }
        { if(!_buf["Vip"].IsNumber) { throw new SerializationException(); }  Vip = _buf["Vip"]; }
    }

    public static Shop DeserializeShop(JSONNode _buf)
    {
        return new Shop(_buf);
    }

    /// <summary>
    /// 商品id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 商品类型
    /// </summary>
    public readonly int Type;
    /// <summary>
    /// 商品内容
    /// </summary>
    public readonly int Items;
    /// <summary>
    /// 商品数量
    /// </summary>
    public readonly long Quantity;
    /// <summary>
    /// 支付数量
    /// </summary>
    public readonly long Payamount;
    /// <summary>
    /// 优惠折扣（%）
    /// </summary>
    public readonly int Discount;
    /// <summary>
    /// 购买次数限制
    /// </summary>
    public readonly int Paytimes;
    /// <summary>
    /// VIP等级
    /// </summary>
    public readonly int Vip;
   
    public const int __ID__ = 2576150;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Type:" + Type + ","
        + "Items:" + Items + ","
        + "Quantity:" + Quantity + ","
        + "Payamount:" + Payamount + ","
        + "Discount:" + Discount + ","
        + "Paytimes:" + Paytimes + ","
        + "Vip:" + Vip + ","
        + "}";
    }
}

}
