
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class ShopConfig
{
    private readonly System.Collections.Generic.Dictionary<int, Shop> _dataMap;
    private readonly System.Collections.Generic.List<Shop> _dataList;
    
    public ShopConfig(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Shop>();
        _dataList = new System.Collections.Generic.List<Shop>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            Shop _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = Shop.DeserializeShop(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Shop> DataMap => _dataMap;
    public System.Collections.Generic.List<Shop> DataList => _dataList;

    public Shop GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Shop Get(int key) => _dataMap[key];
    public Shop this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

