
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class Sounds : Luban.BeanBase
{
    public Sounds(ByteBuf _buf) 
    {
        Id = _buf.ReadString();
        FileName = _buf.ReadString();
    }

    public static Sounds DeserializeSounds(ByteBuf _buf)
    {
        return new Sounds(_buf);
    }

    /// <summary>
    /// 这是id
    /// </summary>
    public readonly string Id;
    /// <summary>
    /// 文件名
    /// </summary>
    public readonly string FileName;
   
    public const int __ID__ = -1812642460;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "FileName:" + FileName + ","
        + "}";
    }
}

}
