
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class StarterPackConfig
{
    private readonly System.Collections.Generic.Dictionary<int, StarterPack> _dataMap;
    private readonly System.Collections.Generic.List<StarterPack> _dataList;
    
    public StarterPackConfig(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, StarterPack>();
        _dataList = new System.Collections.Generic.List<StarterPack>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            StarterPack _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = StarterPack.DeserializeStarterPack(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, StarterPack> DataMap => _dataMap;
    public System.Collections.Generic.List<StarterPack> DataList => _dataList;

    public StarterPack GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public StarterPack Get(int key) => _dataMap[key];
    public StarterPack this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

