
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace cfg
{
public partial class Tables
{
    public GlobalConfig GlobalConfig {get; }
    public LanguageConfig LanguageConfig {get; }
    public SoundsConfig SoundsConfig {get; }
    public HorseConfig HorseConfig {get; }

    public Tables(System.Func<string, ByteBuf> loader)
    {
        GlobalConfig = new GlobalConfig(loader("globalconfig"));
        LanguageConfig = new LanguageConfig(loader("languageconfig"));
        SoundsConfig = new SoundsConfig(loader("soundsconfig"));
        HorseConfig = new HorseConfig(loader("horseconfig"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        GlobalConfig.ResolveRef(this);
        LanguageConfig.ResolveRef(this);
        SoundsConfig.ResolveRef(this);
        HorseConfig.ResolveRef(this);
    }
}

}
