
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class Talent : Luban.BeanBase
{
    public Talent(JSONNode _buf) 
    {
        { if(!_buf["Id"].IsNumber) { throw new SerializationException(); }  Id = _buf["Id"]; }
        { if(!_buf["Level"].IsNumber) { throw new SerializationException(); }  Level = _buf["Level"]; }
        { if(!_buf["Gold"].IsNumber) { throw new SerializationException(); }  Gold = _buf["Gold"]; }
    }

    public static Talent DeserializeTalent(JSONNode _buf)
    {
        return new Talent(_buf);
    }

    /// <summary>
    /// ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 天赋等级
    /// </summary>
    public readonly int Level;
    /// <summary>
    /// 金币数量
    /// </summary>
    public readonly int Gold;
   
    public const int __ID__ = -1797219060;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Level:" + Level + ","
        + "Gold:" + Gold + ","
        + "}";
    }
}

}
