
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class TalentSkill : Luban.BeanBase
{
    public TalentSkill(JSONNode _buf) 
    {
        { if(!_buf["Id"].IsNumber) { throw new SerializationException(); }  Id = _buf["Id"]; }
        { if(!_buf["Lvl"].IsNumber) { throw new SerializationException(); }  Lvl = _buf["Lvl"]; }
        { if(!_buf["NeedGolds"].IsNumber) { throw new SerializationException(); }  NeedGolds = _buf["NeedGolds"]; }
        { if(!_buf["BindSkill"].IsNumber) { throw new SerializationException(); }  BindSkill = _buf["BindSkill"]; }
    }

    public static TalentSkill DeserializeTalentSkill(JSONNode _buf)
    {
        return new TalentSkill(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 天赋技能等级
    /// </summary>
    public readonly int Lvl;
    /// <summary>
    /// 升级金币
    /// </summary>
    public readonly int NeedGolds;
    /// <summary>
    /// 技能
    /// </summary>
    public readonly long BindSkill;
   
    public const int __ID__ = 2033681573;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Lvl:" + Lvl + ","
        + "NeedGolds:" + NeedGolds + ","
        + "BindSkill:" + BindSkill + ","
        + "}";
    }
}

}
