
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class TalentSkillConfig
{
    private readonly System.Collections.Generic.Dictionary<int, TalentSkill> _dataMap;
    private readonly System.Collections.Generic.List<TalentSkill> _dataList;
    
    public TalentSkillConfig(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, TalentSkill>();
        _dataList = new System.Collections.Generic.List<TalentSkill>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            TalentSkill _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = TalentSkill.DeserializeTalentSkill(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, TalentSkill> DataMap => _dataMap;
    public System.Collections.Generic.List<TalentSkill> DataList => _dataList;

    public TalentSkill GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public TalentSkill Get(int key) => _dataMap[key];
    public TalentSkill this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

