
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class TalentConfig
{
    private readonly System.Collections.Generic.Dictionary<int, Talent> _dataMap;
    private readonly System.Collections.Generic.List<Talent> _dataList;
    
    public TalentConfig(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Talent>();
        _dataList = new System.Collections.Generic.List<Talent>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            Talent _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = Talent.DeserializeTalent(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Talent> DataMap => _dataMap;
    public System.Collections.Generic.List<Talent> DataList => _dataList;

    public Talent GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Talent Get(int key) => _dataMap[key];
    public Talent this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

