
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class Tank : Luban.BeanBase
{
    public Tank(JSONNode _buf) 
    {
        { if(!_buf["Id"].IsNumber) { throw new SerializationException(); }  Id = _buf["Id"]; }
        { if(!_buf["Type"].IsNumber) { throw new SerializationException(); }  Type = _buf["Type"]; }
        { if(!_buf["Name"].IsString) { throw new SerializationException(); }  Name = _buf["Name"]; }
        { if(!_buf["Attack"].IsNumber) { throw new SerializationException(); }  Attack = _buf["Attack"]; }
        { if(!_buf["Hp"].IsNumber) { throw new SerializationException(); }  Hp = _buf["Hp"]; }
        { if(!_buf["Movement"].IsNumber) { throw new SerializationException(); }  Movement = _buf["Movement"]; }
        { if(!_buf["Defence"].IsNumber) { throw new SerializationException(); }  Defence = _buf["Defence"]; }
        { if(!_buf["Unlock"].IsNumber) { throw new SerializationException(); }  Unlock = _buf["Unlock"]; }
        { if(!_buf["Txt"].IsString) { throw new SerializationException(); }  Txt = _buf["Txt"]; }
    }

    public static Tank DeserializeTank(JSONNode _buf)
    {
        return new Tank(_buf);
    }

    /// <summary>
    /// 战车id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 品质1蓝2紫3橙
    /// </summary>
    public readonly int Type;
    /// <summary>
    /// 战车名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 攻击
    /// </summary>
    public readonly int Attack;
    /// <summary>
    /// 生命
    /// </summary>
    public readonly int Hp;
    /// <summary>
    /// 移速
    /// </summary>
    public readonly int Movement;
    /// <summary>
    /// 防御
    /// </summary>
    public readonly int Defence;
    /// <summary>
    /// 解锁条件（VIP等级）
    /// </summary>
    public readonly int Unlock;
    /// <summary>
    /// 解锁条件（描述）
    /// </summary>
    public readonly string Txt;
   
    public const int __ID__ = 2599178;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
        
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Type:" + Type + ","
        + "Name:" + Name + ","
        + "Attack:" + Attack + ","
        + "Hp:" + Hp + ","
        + "Movement:" + Movement + ","
        + "Defence:" + Defence + ","
        + "Unlock:" + Unlock + ","
        + "Txt:" + Txt + ","
        + "}";
    }
}

}
