
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class TankConfig
{
    private readonly System.Collections.Generic.Dictionary<int, Tank> _dataMap;
    private readonly System.Collections.Generic.List<Tank> _dataList;
    
    public TankConfig(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Tank>();
        _dataList = new System.Collections.Generic.List<Tank>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            Tank _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = Tank.DeserializeTank(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Tank> DataMap => _dataMap;
    public System.Collections.Generic.List<Tank> DataList => _dataList;

    public Tank GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Tank Get(int key) => _dataMap[key];
    public Tank this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

