
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class Task : Luban.BeanBase
{
    public Task(JSONNode _buf) 
    {
        { if(!_buf["Id"].IsNumber) { throw new SerializationException(); }  Id = _buf["Id"]; }
        { if(!_buf["Description"].IsString) { throw new SerializationException(); }  Description = _buf["Description"]; }
        { if(!_buf["Tapy"].IsNumber) { throw new SerializationException(); }  Tapy = _buf["Tapy"]; }
        { if(!_buf["Quantity"].IsNumber) { throw new SerializationException(); }  Quantity = _buf["Quantity"]; }
        { if(!_buf["Reward"].IsNumber) { throw new SerializationException(); }  Reward = _buf["Reward"]; }
        { if(!_buf["Amount"].IsNumber) { throw new SerializationException(); }  Amount = _buf["Amount"]; }
    }

    public static Task DeserializeTask(JSONNode _buf)
    {
        return new Task(_buf);
    }

    /// <summary>
    /// 任务id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 任务描述
    /// </summary>
    public readonly string Description;
    /// <summary>
    /// 任务类型
    /// </summary>
    public readonly int Tapy;
    /// <summary>
    /// 目标数量
    /// </summary>
    public readonly long Quantity;
    /// <summary>
    /// 奖励
    /// </summary>
    public readonly int Reward;
    /// <summary>
    /// 奖励数量
    /// </summary>
    public readonly int Amount;
   
    public const int __ID__ = 2599333;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Description:" + Description + ","
        + "Tapy:" + Tapy + ","
        + "Quantity:" + Quantity + ","
        + "Reward:" + Reward + ","
        + "Amount:" + Amount + ","
        + "}";
    }
}

}
