
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class TurntableConfig
{
    private readonly System.Collections.Generic.Dictionary<int, Turntable> _dataMap;
    private readonly System.Collections.Generic.List<Turntable> _dataList;
    
    public TurntableConfig(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Turntable>();
        _dataList = new System.Collections.Generic.List<Turntable>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            Turntable _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = Turntable.DeserializeTurntable(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Turntable> DataMap => _dataMap;
    public System.Collections.Generic.List<Turntable> DataList => _dataList;

    public Turntable GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Turntable Get(int key) => _dataMap[key];
    public Turntable this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

