
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class Turntable : Luban.BeanBase
{
    public Turntable(JSONNode _buf) 
    {
        { if(!_buf["Id"].IsNumber) { throw new SerializationException(); }  Id = _buf["Id"]; }
        { if(!_buf["Items"].IsNumber) { throw new SerializationException(); }  Items = _buf["Items"]; }
        { if(!_buf["Quantity"].IsNumber) { throw new SerializationException(); }  Quantity = _buf["Quantity"]; }
        { if(!_buf["Probability"].IsNumber) { throw new SerializationException(); }  Probability = _buf["Probability"]; }
        { if(!_buf["Probability2"].IsNumber) { throw new SerializationException(); }  Probability2 = _buf["Probability2"]; }
    }

    public static Turntable DeserializeTurntable(JSONNode _buf)
    {
        return new Turntable(_buf);
    }

    /// <summary>
    /// 这是id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 道具内容
    /// </summary>
    public readonly int Items;
    /// <summary>
    /// 名字
    /// </summary>
    public readonly int Quantity;
    /// <summary>
    /// 概率(%)
    /// </summary>
    public readonly int Probability;
    /// <summary>
    /// 概率(%)
    /// </summary>
    public readonly int Probability2;
   
    public const int __ID__ = 1898553681;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Items:" + Items + ","
        + "Quantity:" + Quantity + ","
        + "Probability:" + Probability + ","
        + "Probability2:" + Probability2 + ","
        + "}";
    }
}

}
