
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class Vip : Luban.BeanBase
{
    public Vip(JSONNode _buf) 
    {
        { if(!_buf["Id"].IsNumber) { throw new SerializationException(); }  Id = _buf["Id"]; }
        { if(!_buf["Exp"].IsNumber) { throw new SerializationException(); }  Exp = _buf["Exp"]; }
        { if(!_buf["Reward"].IsNumber) { throw new SerializationException(); }  Reward = _buf["Reward"]; }
        { if(!_buf["Txt1"].IsString) { throw new SerializationException(); }  Txt1 = _buf["Txt1"]; }
        { if(!_buf["Txt2"].IsString) { throw new SerializationException(); }  Txt2 = _buf["Txt2"]; }
    }

    public static Vip DeserializeVip(JSONNode _buf)
    {
        return new Vip(_buf);
    }

    /// <summary>
    /// vip等级
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 升级经验
    /// </summary>
    public readonly int Exp;
    /// <summary>
    /// 每日宝箱奖励
    /// </summary>
    public readonly int Reward;
    /// <summary>
    /// 特权描述1
    /// </summary>
    public readonly string Txt1;
    /// <summary>
    /// 特权描述2
    /// </summary>
    public readonly string Txt2;
   
    public const int __ID__ = 86013;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Exp:" + Exp + ","
        + "Reward:" + Reward + ","
        + "Txt1:" + Txt1 + ","
        + "Txt2:" + Txt2 + ","
        + "}";
    }
}

}
