
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class VipConfig
{
    private readonly System.Collections.Generic.Dictionary<int, Vip> _dataMap;
    private readonly System.Collections.Generic.List<Vip> _dataList;
    
    public VipConfig(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Vip>();
        _dataList = new System.Collections.Generic.List<Vip>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            Vip _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = Vip.DeserializeVip(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Vip> DataMap => _dataMap;
    public System.Collections.Generic.List<Vip> DataList => _dataList;

    public Vip GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Vip Get(int key) => _dataMap[key];
    public Vip this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

