
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class VipGift : Luban.BeanBase
{
    public VipGift(JSONNode _buf) 
    {
        { if(!_buf["Id"].IsNumber) { throw new SerializationException(); }  Id = _buf["Id"]; }
        { if(!_buf["Viplevel"].IsNumber) { throw new SerializationException(); }  Viplevel = _buf["Viplevel"]; }
        { var __json0 = _buf["Reward"]; if(!__json0.IsArray) { throw new SerializationException(); } Reward = new System.Collections.Generic.List<ItemExchange>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { ItemExchange __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = ItemExchange.DeserializeItemExchange(__e0);  }  Reward.Add(__v0); }   }
        { if(!_buf["GiftNumber"].IsNumber) { throw new SerializationException(); }  GiftNumber = _buf["GiftNumber"]; }
    }

    public static VipGift DeserializeVipGift(JSONNode _buf)
    {
        return new VipGift(_buf);
    }

    /// <summary>
    /// 奖励id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// VIP等级
    /// </summary>
    public readonly int Viplevel;
    /// <summary>
    /// 奖励内容
    /// </summary>
    public readonly System.Collections.Generic.List<ItemExchange> Reward;
    /// <summary>
    /// 礼包数量
    /// </summary>
    public readonly int GiftNumber;
   
    public const int __ID__ = 2127619789;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        foreach (var _e in Reward) { _e?.ResolveRef(tables); }
        
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Viplevel:" + Viplevel + ","
        + "Reward:" + Luban.StringUtil.CollectionToString(Reward) + ","
        + "GiftNumber:" + GiftNumber + ","
        + "}";
    }
}

}
