
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class VipGiftConfig
{
    private readonly System.Collections.Generic.Dictionary<int, VipGift> _dataMap;
    private readonly System.Collections.Generic.List<VipGift> _dataList;
    
    public VipGiftConfig(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, VipGift>();
        _dataList = new System.Collections.Generic.List<VipGift>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            VipGift _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = VipGift.DeserializeVipGift(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, VipGift> DataMap => _dataMap;
    public System.Collections.Generic.List<VipGift> DataList => _dataList;

    public VipGift GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public VipGift Get(int key) => _dataMap[key];
    public VipGift this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

