
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class ZeroDollarPurchase : Luban.BeanBase
{
    public ZeroDollarPurchase(JSONNode _buf) 
    {
        { if(!_buf["Id"].IsNumber) { throw new SerializationException(); }  Id = _buf["Id"]; }
        { if(!_buf["Name"].IsString) { throw new SerializationException(); }  Name = _buf["Name"]; }
        { if(!_buf["MagicCoins"].IsNumber) { throw new SerializationException(); }  MagicCoins = _buf["MagicCoins"]; }
        { if(!_buf["MagicStone"].IsNumber) { throw new SerializationException(); }  MagicStone = _buf["MagicStone"]; }
        { if(!_buf["TaskNum"].IsNumber) { throw new SerializationException(); }  TaskNum = _buf["TaskNum"]; }
        { if(!_buf["Price"].IsNumber) { throw new SerializationException(); }  Price = _buf["Price"]; }
        { if(!_buf["Time"].IsNumber) { throw new SerializationException(); }  Time = _buf["Time"]; }
        { var __json0 = _buf["TaskProgress"]; if(!__json0.IsArray) { throw new SerializationException(); } TaskProgress = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  TaskProgress.Add(__v0); }   }
        { var __json0 = _buf["StageReward"]; if(!__json0.IsArray) { throw new SerializationException(); } StageReward = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  StageReward.Add(__v0); }   }
    }

    public static ZeroDollarPurchase DeserializeZeroDollarPurchase(JSONNode _buf)
    {
        return new ZeroDollarPurchase(_buf);
    }

    /// <summary>
    /// 礼包id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 礼包名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 魔币奖励
    /// </summary>
    public readonly int MagicCoins;
    /// <summary>
    /// 魔导石奖励（展示）
    /// </summary>
    public readonly int MagicStone;
    /// <summary>
    /// 任务目标数量
    /// </summary>
    public readonly long TaskNum;
    /// <summary>
    /// 礼包价格
    /// </summary>
    public readonly int Price;
    /// <summary>
    /// 任务时间/h
    /// </summary>
    public readonly int Time;
    /// <summary>
    /// 任务进度%
    /// </summary>
    public readonly System.Collections.Generic.List<int> TaskProgress;
    /// <summary>
    /// 阶段奖励数量
    /// </summary>
    public readonly System.Collections.Generic.List<int> StageReward;
   
    public const int __ID__ = -761448763;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
        
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Name:" + Name + ","
        + "MagicCoins:" + MagicCoins + ","
        + "MagicStone:" + MagicStone + ","
        + "TaskNum:" + TaskNum + ","
        + "Price:" + Price + ","
        + "Time:" + Time + ","
        + "TaskProgress:" + Luban.StringUtil.CollectionToString(TaskProgress) + ","
        + "StageReward:" + Luban.StringUtil.CollectionToString(StageReward) + ","
        + "}";
    }
}

}
