
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class ZeroDollarPurchaseConfig
{
    private readonly System.Collections.Generic.Dictionary<int, ZeroDollarPurchase> _dataMap;
    private readonly System.Collections.Generic.List<ZeroDollarPurchase> _dataList;
    
    public ZeroDollarPurchaseConfig(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, ZeroDollarPurchase>();
        _dataList = new System.Collections.Generic.List<ZeroDollarPurchase>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            ZeroDollarPurchase _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = ZeroDollarPurchase.DeserializeZeroDollarPurchase(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, ZeroDollarPurchase> DataMap => _dataMap;
    public System.Collections.Generic.List<ZeroDollarPurchase> DataList => _dataList;

    public ZeroDollarPurchase GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public ZeroDollarPurchase Get(int key) => _dataMap[key];
    public ZeroDollarPurchase this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

