
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class Zpgift : Luban.BeanBase
{
    public Zpgift(JSONNode _buf) 
    {
        { if(!_buf["Id"].IsNumber) { throw new SerializationException(); }  Id = _buf["Id"]; }
        { if(!_buf["Name"].IsString) { throw new SerializationException(); }  Name = _buf["Name"]; }
        { if(!_buf["Reward1"].IsNumber) { throw new SerializationException(); }  Reward1 = _buf["Reward1"]; }
        { if(!_buf["Reward2"].IsNumber) { throw new SerializationException(); }  Reward2 = _buf["Reward2"]; }
        { if(!_buf["Price"].IsNumber) { throw new SerializationException(); }  Price = _buf["Price"]; }
        { if(!_buf["Probability"].IsNumber) { throw new SerializationException(); }  Probability = _buf["Probability"]; }
    }

    public static Zpgift DeserializeZpgift(JSONNode _buf)
    {
        return new Zpgift(_buf);
    }

    /// <summary>
    /// 礼包id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 礼包名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 夺宝券数量
    /// </summary>
    public readonly int Reward1;
    /// <summary>
    /// 晶币数量
    /// </summary>
    public readonly int Reward2;
    /// <summary>
    /// 礼包价格
    /// </summary>
    public readonly int Price;
    /// <summary>
    /// 每日限购次数
    /// </summary>
    public readonly int Probability;
   
    public const int __ID__ = -1611736698;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Name:" + Name + ","
        + "Reward1:" + Reward1 + ","
        + "Reward2:" + Reward2 + ","
        + "Price:" + Price + ","
        + "Probability:" + Probability + ","
        + "}";
    }
}

}
