
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class ZpgiftConfig
{
    private readonly System.Collections.Generic.Dictionary<int, Zpgift> _dataMap;
    private readonly System.Collections.Generic.List<Zpgift> _dataList;
    
    public ZpgiftConfig(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Zpgift>();
        _dataList = new System.Collections.Generic.List<Zpgift>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            Zpgift _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = Zpgift.DeserializeZpgift(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Zpgift> DataMap => _dataMap;
    public System.Collections.Generic.List<Zpgift> DataList => _dataList;

    public Zpgift GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Zpgift Get(int key) => _dataMap[key];
    public Zpgift this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

