
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class Zpreward : Luban.BeanBase
{
    public Zpreward(JSONNode _buf) 
    {
        { if(!_buf["Id"].IsNumber) { throw new SerializationException(); }  Id = _buf["Id"]; }
        { if(!_buf["Items"].IsNumber) { throw new SerializationException(); }  Items = _buf["Items"]; }
        { if(!_buf["Quantity"].IsNumber) { throw new SerializationException(); }  Quantity = _buf["Quantity"]; }
        { if(!_buf["Times"].IsNumber) { throw new SerializationException(); }  Times = _buf["Times"]; }
        { if(!_buf["IsItem"].IsNumber) { throw new SerializationException(); }  IsItem = _buf["IsItem"]; }
        { if(!_buf["Seat"].IsNumber) { throw new SerializationException(); }  Seat = _buf["Seat"]; }
        { if(!_buf["Probability2"].IsNumber) { throw new SerializationException(); }  Probability2 = _buf["Probability2"]; }
        { if(!_buf["ShowIndex"].IsNumber) { throw new SerializationException(); }  ShowIndex = _buf["ShowIndex"]; }
    }

    public static Zpreward DeserializeZpreward(JSONNode _buf)
    {
        return new Zpreward(_buf);
    }

    /// <summary>
    /// 奖励id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 道具内容
    /// </summary>
    public readonly int Items;
    /// <summary>
    /// 数量
    /// </summary>
    public readonly int Quantity;
    /// <summary>
    /// 保底次数（0为没有保底）
    /// </summary>
    public readonly int Times;
    /// <summary>
    /// 是否是道具
    /// </summary>
    public readonly int IsItem;
    /// <summary>
    /// 转盘位置
    /// </summary>
    public readonly int Seat;
    /// <summary>
    /// 概率/100
    /// </summary>
    public readonly int Probability2;
    /// <summary>
    /// 显示优先级()
    /// </summary>
    public readonly int ShowIndex;
   
    public const int __ID__ = 1915945477;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Items:" + Items + ","
        + "Quantity:" + Quantity + ","
        + "Times:" + Times + ","
        + "IsItem:" + IsItem + ","
        + "Seat:" + Seat + ","
        + "Probability2:" + Probability2 + ","
        + "ShowIndex:" + ShowIndex + ","
        + "}";
    }
}

}
