
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class ZprewardConfig
{
    private readonly System.Collections.Generic.Dictionary<int, Zpreward> _dataMap;
    private readonly System.Collections.Generic.List<Zpreward> _dataList;
    
    public ZprewardConfig(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Zpreward>();
        _dataList = new System.Collections.Generic.List<Zpreward>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            Zpreward _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = Zpreward.DeserializeZpreward(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Zpreward> DataMap => _dataMap;
    public System.Collections.Generic.List<Zpreward> DataList => _dataList;

    public Zpreward GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Zpreward Get(int key) => _dataMap[key];
    public Zpreward this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

