
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class Zptask : Luban.BeanBase
{
    public Zptask(JSONNode _buf) 
    {
        { if(!_buf["Id"].IsNumber) { throw new SerializationException(); }  Id = _buf["Id"]; }
        { if(!_buf["Description"].IsString) { throw new SerializationException(); }  Description = _buf["Description"]; }
        { if(!_buf["Quantity"].IsNumber) { throw new SerializationException(); }  Quantity = _buf["Quantity"]; }
        { if(!_buf["Reward"].IsNumber) { throw new SerializationException(); }  Reward = _buf["Reward"]; }
        { if(!_buf["Type"].IsNumber) { throw new SerializationException(); }  Type = _buf["Type"]; }
    }

    public static Zptask DeserializeZptask(JSONNode _buf)
    {
        return new Zptask(_buf);
    }

    /// <summary>
    /// 任务id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 任务描述
    /// </summary>
    public readonly string Description;
    /// <summary>
    /// 目标数量
    /// </summary>
    public readonly int Quantity;
    /// <summary>
    /// 奖励抽奖券数量
    /// </summary>
    public readonly int Reward;
    /// <summary>
    /// 任务类型
    /// </summary>
    public readonly int Type;
   
    public const int __ID__ = -1611356709;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Description:" + Description + ","
        + "Quantity:" + Quantity + ","
        + "Reward:" + Reward + ","
        + "Type:" + Type + ","
        + "}";
    }
}

}
