
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class ZptaskConfig
{
    private readonly System.Collections.Generic.Dictionary<int, Zptask> _dataMap;
    private readonly System.Collections.Generic.List<Zptask> _dataList;
    
    public ZptaskConfig(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Zptask>();
        _dataList = new System.Collections.Generic.List<Zptask>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            Zptask _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = Zptask.DeserializeZptask(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Zptask> DataMap => _dataMap;
    public System.Collections.Generic.List<Zptask> DataList => _dataList;

    public Zptask GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Zptask Get(int key) => _dataMap[key];
    public Zptask this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

